/* Staged selection: cancel never edits; confirm writes storage before canonical state. */
(function(){
 'use strict';
 const S=FloorPlanSurfaces,dialog=document.createElement('dialog');dialog.id='surfaceDialog';dialog.className='surface-library';dialog.setAttribute('aria-labelledby','surfaceTitle');document.body.append(dialog);
 const qa=document.createElement('p');qa.id='surfaceQAStatus';qa.setAttribute('role','status');qa.setAttribute('aria-live','polite');document.getElementById('stage').append(qa);
 let target,chosen,baseline,owner,returnFocus,search,family,cards,details,error,applyButton,rx,ry,wallSelect,comparison,lastChoice;
 function el(tag,text,parent=dialog){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;parent.append(e);return e;}
 function button(id,text,fn,parent=dialog){const b=el('button',text,parent);b.type='button';b.id=id;b.className='btn';b.onclick=fn;return b;}
 function input(id,text,type,parent){const l=el('label',text,parent),e=el('input',undefined,l);e.id=id;e.type=type;return e;}
 function select(id,text,rows,parent){const l=el('label',text,parent),e=el('select',undefined,l);e.id=id;for(const [value,name]of rows){const o=el('option',name,e);o.value=value;}return e;}
 function close(){dialog.close();returnFocus?.focus();chosen=null;}
 function messages(){const unknown=project.materials.filter(m=>m.appearance.preset?.startsWith('surface-')&&!S.get(m.appearance.preset)).map(m=>'Acabado desconocido: '+m.appearance.preset+'; se muestra el color de respaldo.');qa.textContent=[...S.status.values(),...unknown].join(' ');}
 addEventListener('surface-status',messages);S.ready.then(()=>{renderAll();window.View3D?.refreshSurfaces();messages();});
 function describe(id,node){const r=project.rooms.find(r=>r.id===id),m=project.materials.find(m=>m.id===r?.floorMaterialId);if(!m)return;node.textContent='Suelo actual: '+nm(m.name)+(m.appearance.preset?.startsWith('surface-')&&!S.get(m.appearance.preset)?' · desconocido, color de respaldo.':'');}
 function render(){cards.replaceChildren();const list=S.search(S.entries,{family:family.value,query:search.value,application:target.kind});for(const entry of list){const b=button('',entry.name,()=>choose(entry),cards);b.className='surface-card';b.dataset.surface=entry.id;b.setAttribute('aria-pressed',String(chosen?.id===entry.id));const image=document.createElement('img');image.src=entry.sample.path;image.loading='lazy';image.width=entry.sample.width;image.height=entry.sample.height;image.alt=entry.name;image.onerror=()=>{b.disabled=true;S.notify(entry.id,'Muestra no disponible: '+entry.sample.path);if(chosen?.id===entry.id){applyButton.disabled=true;error.textContent='La muestra no pudo cargarse; elige otro acabado.';}};b.prepend(image);el('span',S.families[entry.family],b);}if(!list.length)el('p','No hay acabados verificados para esta búsqueda/superficie.',cards);}
 function picture(entry,text){const f=el('figure',undefined,comparison);if(entry){const im=el('img',undefined,f);im.src=entry.sample.path;im.alt=entry.name;}el('figcaption',text,f);}
 function choose(entry){comparison.replaceChildren();picture(lastChoice,'Selección anterior: '+(lastChoice?.name||'—'));picture(entry,'Candidata: '+entry.name);lastChoice=entry;chosen=entry;rx.value=entry.repeatMm.x;ry.value=entry.repeatMm.y;details.replaceChildren();el('p',`${entry.source.author} · ${entry.source.license} · ${(entry.maps.baseColor.bytes/1024).toFixed(1)} KiB · ${entry.maps.baseColor.width} × ${entry.maps.baseColor.height} px`,details);const a=el('a','Procedencia y licencia',details);a.href=entry.source.licenseUrl;a.target='_blank';a.rel='noopener';el('p','Repetición inicial de diseño, no medida publicada del producto. Puedes ajustarla en mm.',details);applyButton.disabled=false;error.textContent='';render();}
 function confirm(){try{if(snap()!==baseline||library?.activeId()!==owner)throw Error('El proyecto cambió; cancela y vuelve a abrir la biblioteca.');if(!chosen)throw Error('Elige un acabado');const id=target.kind==='wall'?wallSelect.value:target.id,next=S.apply(project,chosen,{kind:target.kind,id,repeatMm:{x:Number(rx.value),y:Number(ry.value)}});next.updatedAt=new Date(Math.max(Date.now(),Date.parse(next.createdAt))).toISOString();Core.validate(next);storage.setItem(STORE,JSON.stringify(next));project=next;undoStack.push(baseline);if(undoStack.length>150)undoStack.shift();redoStack.length=0;refreshProject();renderAll();window.View3D?.refreshSurfaces();close();closeDrawers();messages();}catch(e){error.textContent=e.message;}}
 async function open(value){returnFocus=document.activeElement;await S.ready;target=value;baseline=snap();owner=library?.activeId();chosen=null;lastChoice=null;dialog.replaceChildren();const h=el('h2','Biblioteca de acabados');h.id='surfaceTitle';el('p',`${S.entries.length} acabados verificados${S.partial?' · biblioteca parcial; objetivo pendiente: 50, diez por familia.':' · cinco familias de diez. Selecciona y compara antes de aplicar.'}`);const controls=el('div');controls.className='surface-controls';search=input('surfaceSearch','Buscar acabado','search',controls);family=select('surfaceFamily','Familia',[['','Todas'],...Object.entries(S.families)],controls);search.oninput=family.onchange=render;
  if(target.kind==='wall'){const rows=project.walls.filter(w=>w.status!=='demolished').map(w=>[w.id,`${w.id} · (${w.start.x}, ${w.start.y}) → (${w.end.x}, ${w.end.y}) mm`]);wallSelect=select('surfaceWallTarget','Pared completa',rows,dialog);el('p','Se aplica a toda la pared y a ambas caras, incluidos los fragmentos junto a huecos. Si es compartida, también cambia la cara de la estancia vecina. No se modifica geometría.');wallSelect.onchange=()=>{chosen=null;applyButton.disabled=true;render();};}
  cards=el('div');cards.className='surface-cards';cards.id='surfaceCards';comparison=el('div');comparison.className='surface-comparison';details=el('div');details.className='surface-detail';const scale=el('div');scale.className='surface-controls';rx=input('surfaceRepeatX','Repetición X (mm)','number',scale);ry=input('surfaceRepeatY','Repetición Y (mm)','number',scale);for(const n of [rx,ry]){n.min=100;n.max=10000;n.step=1;n.value=1000;}error=el('p');error.id='surfaceError';error.className='surface-error';error.setAttribute('role','alert');const actions=el('div');actions.className='actions';applyButton=button('surfaceApply','Aplicar acabado',confirm,actions);applyButton.className+=' primary';applyButton.disabled=true;button('surfaceCancel','Cancelar',close,actions);if(target.kind==='wall')button('surfaceWallDefault','Restaurar pared original',()=>{try{if(snap()!==baseline||library?.activeId()!==owner)throw Error('El proyecto cambió');const next=Core.clone(project);delete next.walls.find(w=>w.id===wallSelect.value).surfaceMaterialId;next.updatedAt=new Date().toISOString();Core.validate(next);storage.setItem(STORE,JSON.stringify(next));project=next;undoStack.push(baseline);redoStack.length=0;renderAll();window.View3D?.refreshSurfaces();close();}catch(e){error.textContent=e.message;}},actions);render();if(S.status.has('catalog'))error.textContent=S.status.get('catalog');dialog.showModal();search.focus();
 }
 dialog.addEventListener('cancel',()=>{chosen=null;returnFocus?.focus();});window.FloorPlanSurfaceUI={open,describe};
})();
