/* F1b UI integrates the existing editor/history/renderers; persistent data never live here. */
(function(){
 const T=FloorPlanTracing,P=FloorPlanPackage,I=FloorPlanImages,A=FloorPlanWallAssist,R=FloorPlanRawWallExport;
 let mode='navigate',points=[],editing=null,shown=false,lastId=library?.activeId(),lastRoot=project.id,operation=0,distanceMode,selectedImage;
 const urls=new Map(),loading=new Set();
 let rawSession=null,rawExportReason='Analiza una imagen calibrada antes de exportar.',exportSerial;
 function invalidateRaw(reason){rawSession=null;rawExportReason=reason;const b=$('#assistRawExport');if(b){b.disabled=true;b.title=reason;}if(rawDialog.open){rawDialog.close();rawForm.reset();}}
 const rawDialog=document.createElement('dialog');rawDialog.id='rawExportDialog';rawDialog.setAttribute('aria-labelledby','rawExportTitle');
 const rawTitle=document.createElement('h2');rawTitle.id='rawExportTitle';rawTitle.textContent='Exportar sugerencias para evaluación';rawDialog.append(rawTitle);
 const rawNote=document.createElement('p');rawNote.textContent='Descarga privada voluntaria. No incluye imagen ni proyecto. Referencias ausentes: no es una evaluación. No compartas archivos reales en GitHub/Vercel.';rawDialog.append(rawNote);
 const rawDetails=document.createElement('p');rawDetails.id='rawExportDetails';rawDetails.style.overflowWrap='anywhere';rawDialog.append(rawDetails);
 const rawForm=document.createElement('form');rawForm.autocomplete='off';rawDialog.append(rawForm);const rawFields={};
 for(const [key,text,options]of [['dataset_id','Revisión del conjunto (eval_NNN)',null],['case_id','ID opaco del caso (case_NNN)',null],['type','Tipo de plano',[['digital','Exportación digital'],['scan','Escaneo'],['photo','Foto']]],['data_kind','Origen de los datos',[['synthetic','Fixture sintética'],['real','Datos reales privados']]]]){
  const label=document.createElement('label');label.textContent=text;const input=document.createElement(options?'select':'input');input.id='raw-'+key;input.required=true;
  if(options){const empty=document.createElement('option');empty.value='';empty.textContent='Selecciona explícitamente';input.append(empty);for(const [value,name]of options){const o=document.createElement('option');o.value=value;o.textContent=name;input.append(o);}}else{input.type='text';input.maxLength=8;input.pattern=key==='dataset_id'?'eval_[0-9]{3}':'case_[0-9]{3}';input.autocomplete='off';}
  label.append(input);rawForm.append(label);rawFields[key]=input;
 }
 const rawSave=document.createElement('button');rawSave.id='rawExportSave';rawSave.className='btn primary';rawSave.textContent='Descargar instantánea cruda';rawForm.append(rawSave);
 const rawCancel=document.createElement('button');rawCancel.id='rawExportCancel';rawCancel.type='button';rawCancel.className='btn';rawCancel.textContent='Cancelar';rawCancel.onclick=()=>{rawDialog.close();rawForm.reset();};rawForm.append(rawCancel);
 const rawError=document.createElement('p');rawError.id='rawExportError';rawError.setAttribute('role','alert');rawForm.append(rawError);document.body.append(rawDialog);rawDialog.addEventListener('cancel',()=>rawForm.reset());
 function openRawExport(){checkAssist();if(!rawSession||!candidates.length)throw Error(rawExportReason);exportSerial=assistSerial;rawForm.reset();rawError.textContent='';rawDetails.textContent=`${rawSession.predictions.length} segmentos crudos · image-aligned-mm · ${rawSession.scale_applied.mm_per_pixel} mm/píxel · escala ${rawSession.scale_applied.confidence} · detector ${rawSession.detector_commit}`;rawDialog.showModal();rawFields.dataset_id.focus();}
 rawForm.onsubmit=e=>{e.preventDefault();try{checkAssist();if(!rawSession||exportSerial!==assistSerial||!candidates.length)throw Error('La sesión cambió. Vuelve a analizar y exporta antes de revisar.');const record=R.build(rawSession,Object.fromEntries(Object.entries(rawFields).map(([k,input])=>[k,input.value])));download('sugerencias-crudas-evaluacion.json',new Blob([JSON.stringify(record,null,2)],{type:'application/json'}));rawDialog.close();rawForm.reset();status('Instantánea privada descargada. Añade referencias solo en una copia local; F2 sigue sin validar.');}catch(err){rawError.textContent=err.message;}};

 let candidates=[],assistKey=null,assistSerial=0,analyzing=false,correcting=null;
 function referenceKey(){return JSON.stringify([library?.activeId(),project.id,image(),project.scale]);}
 function clearAssist(){invalidateRaw('La sesión cambió o se canceló; vuelve a analizar.');$('#assistRawExport')?.remove();assistSerial++;analyzing=false;candidates=[];assistKey=null;correcting=null;if(assistDialog.open)assistDialog.close();$('#gAssist').replaceChildren();$('#assistCandidates')?.replaceChildren();}
 function checkAssist(){if(assistKey!==null&&assistKey!==referenceKey())clearAssist();}
 function drawAssist(){const g=$('#gAssist');g.replaceChildren();candidates.forEach((c,n)=>{const line=document.createElementNS(svg.namespaceURI,'line');for(const [key,value]of Object.entries({x1:c.start.x,y1:c.start.y,x2:c.end.x,y2:c.end.y,stroke:'#7c3aed','stroke-width':3/view.s,'stroke-dasharray':`${8/view.s} ${5/view.s}`}))line.setAttribute(key,value);g.append(line);const label=document.createElementNS(svg.namespaceURI,'text');label.setAttribute('x',(c.start.x+c.end.x)/2);label.setAttribute('y',(c.start.y+c.end.y)/2-8/view.s);label.setAttribute('font-size',14/view.s);label.setAttribute('fill','#7c3aed');label.textContent=`S${n+1}`;g.append(label);});}
 async function analyze(){let bitmap,serial;try{
  if(is3D())await setView('2d');cancel();const selected=image();if(!selected)throw Error('Importa una imagen local primero.');const im=Core.clone(selected);
  if(!im?.placement||im.storage.kind!=='local-browser')throw Error('Importa y coloca una imagen local primero.');
  serial=++assistSerial;const key=referenceKey(),initial=snap();assistKey=key;analyzing=true;render();status('Analizando localmente; puedes cancelar y seguir trazando manualmente.');
  const blob=await I.get(im.storage.ref||im.id);if(!blob)throw Error('Imagen local no disponible. Importa su ZIP.');
  const bytes=new Uint8Array(await blob.arrayBuffer()),info=T.imageInfo(bytes,im.mediaType);if(info.widthPx!==im.widthPx||info.heightPx!==im.heightPx)throw Error('La referencia no coincide con la imagen local.');
  bitmap=await createImageBitmap(new Blob([T.renderBytes(bytes,info)],{type:im.mediaType}));
  const factor=Math.min(1,A.MAX_SIDE/Math.max(im.widthPx,im.heightPx)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(im.widthPx*factor));canvas.height=Math.max(1,Math.round(im.heightPx*factor));
  const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)throw Error('No se puede procesar esta imagen localmente.');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);
  // Yield once so cancel/manual controls remain usable before bounded CPU work.
  await new Promise(resolve=>requestAnimationFrame(resolve));
  if(serial!==assistSerial||key!==referenceKey()||initial!==snap())return;
  const result=A.detect(ctx.getImageData(0,0,canvas.width,canvas.height));
  try{rawSession=R.capture(result,im,canvas.width,canvas.height,project.scale);rawExportReason='';}catch(err){invalidateRaw(err.message);}
  candidates=result.map(c=>A.toWorld(c,im,canvas.width,canvas.height));analyzing=false;render();status(candidates.length?`${candidates.length} sugerencias experimentales. Revisa cada segmento; no son muros confirmados.`:'Sin candidatos. Continúa con el trazado manual.');
 }catch(e){if(serial===undefined||serial===assistSerial){clearAssist();render();report(e);}}finally{bitmap?.close();if(serial===assistSerial&&analyzing){analyzing=false;render();}}}
 function acceptCandidate(c,start=c.start,end=c.end){checkAssist();if(!candidates.includes(c))throw Error('La sugerencia ya no está disponible. Vuelve a analizar.');apply(p=>A.accept(p,c,start,end));invalidateRaw('Ya hay revisión humana. Vuelve a analizar para una nueva instantánea cruda.');candidates=candidates.filter(x=>x!==c);render();status('Muro aceptado con revisión humana y procedencia experimental. La escala no ha cambiado.');}
 const assistDialog=document.createElement('dialog');assistDialog.id='assistCorrection';assistDialog.setAttribute('aria-labelledby','assistCorrectionTitle');
 const heading=document.createElement('h2');heading.id='assistCorrectionTitle';heading.textContent='Corregir sugerencia experimental';assistDialog.append(heading);
 const description=document.createElement('p');description.textContent='Revisa los extremos en mm. Guardar confirma solo este muro; no confirma escala ni exactitud.';assistDialog.append(description);
 const assistForm=document.createElement('form');assistDialog.append(assistForm);const correctionInputs={};
 for(const [key,label]of [['startX','Inicio X'],['startY','Inicio Y'],['endX','Fin X'],['endY','Fin Y']]){const l=document.createElement('label');l.textContent=label+' (mm)';l.style.display='block';const input=document.createElement('input');input.type='number';input.required=true;input.step='1';input.min='-1000000';input.max='1000000';input.id='assist-'+key;input.style.cssText='width:100%;padding:8px;font-size:16px';l.append(input);assistForm.append(l);correctionInputs[key]=input;}
 const correctionSave=document.createElement('button');correctionSave.id='assistCorrectionSave';correctionSave.className='btn primary';correctionSave.textContent='Aceptar muro corregido';assistForm.append(correctionSave);
 const correctionCancel=document.createElement('button');correctionCancel.id='assistCorrectionCancel';correctionCancel.type='button';correctionCancel.className='btn';correctionCancel.textContent='Cancelar';correctionCancel.onclick=()=>{correcting=null;assistDialog.close();};assistForm.append(correctionCancel);
 const correctionError=document.createElement('p');correctionError.id='assistCorrectionError';correctionError.setAttribute('role','alert');assistForm.append(correctionError);document.body.append(assistDialog);
 assistForm.onsubmit=e=>{e.preventDefault();try{const c=correcting;acceptCandidate(c,{x:Number(correctionInputs.startX.value),y:Number(correctionInputs.startY.value)},{x:Number(correctionInputs.endX.value),y:Number(correctionInputs.endY.value)});correcting=null;assistDialog.close();}catch(err){correctionError.textContent=err.message;}};
 function assistPanel(panel){const section=document.createElement('section');section.id='wallAssist';const h=document.createElement('h4');h.textContent='Muros · asistencia experimental';section.append(h);const note=document.createElement('p');note.textContent='Solo líneas horizontales/verticales. Cada sugerencia requiere revisión humana. No detecta habitaciones ni huecos.';section.append(note);
  const button=(id,text,fn,container=section)=>{const b=document.createElement('button');b.id=id;b.className='btn';b.textContent=text;b.onclick=()=>{try{fn();}catch(e){report(e);}};container.append(b);return b;};
  button('assistAnalyze',analyzing?'Analizando…':'Sugerir muros localmente',analyze).disabled=analyzing;
  button('assistCancel','Descartar todas / cancelar',()=>{clearAssist();render();status('Sugerencias descartadas. La geometría se conserva.');});
  if(candidates.length){const b=button('assistRawExport','Exportar sugerencias para evaluación',openRawExport);b.disabled=!rawSession;b.title=rawExportReason;if(!rawSession){const reason=document.createElement('p');reason.id='rawExportUnavailable';reason.textContent=rawExportReason;section.append(reason);}}
  const list=document.createElement('div');list.id='assistCandidates';list.style.cssText='max-height:240px;overflow:auto';section.append(list);
  candidates.forEach((c,n)=>{const row=document.createElement('div');row.style.cssText='margin:8px 0;border-top:1px solid var(--line)';const title=document.createElement('p');title.textContent=`S${n+1} · (${c.start.x}, ${c.start.y}) → (${c.end.x}, ${c.end.y}) mm · sin confirmar`;row.append(title);
   button(`assistAccept-${c.id}`,`Aceptar S${n+1}`,()=>acceptCandidate(c),row);
   button(`assistCorrect-${c.id}`,`Corregir S${n+1}`,()=>{correcting=c;correctionError.textContent='';for(const [key,value]of Object.entries({startX:c.start.x,startY:c.start.y,endX:c.end.x,endY:c.end.y}))correctionInputs[key].value=value;assistDialog.showModal();correctionInputs.startX.focus();},row);
   button(`assistReject-${c.id}`,`Rechazar S${n+1}`,()=>{invalidateRaw('Ya hay revisión humana. Vuelve a analizar para exportar.');candidates=candidates.filter(x=>x!==c);render();status('Sugerencia rechazada. La geometría se conserva.');},row);list.append(row);
  });panel.append(section);
 }

 const image=()=>project.sourceImages?.find(i=>i.id===selectedImage)||project.sourceImages?.[0];
 function viewChanged(){$('#traceStatus').hidden=is3D();$('#tip').hidden=!is3D()&&!!$('#traceStatus').textContent;}
 const status=text=>{$('#traceStatus').textContent=text;$('#traceStatus').title=text;viewChanged();};
 function report(e){toast(e.message||String(e),6000);status(e.message||String(e));}
 function apply(fn){const next=Core.clone(project),before=snap();fn(next);next.updatedAt=new Date(Math.max(Date.now(),Date.parse(next.createdAt))).toISOString();Core.validate(next);storage.setItem(STORE,JSON.stringify(next));project=next;undoStack.push(before);if(undoStack.length>150)undoStack.shift();redoStack.length=0;refreshProject();renderAll();return next;}
 async function decode(bytes,info){let bitmap;try{bitmap=await createImageBitmap(new Blob([T.renderBytes(bytes,info)],{type:info.mediaType}));}catch{throw Error('La imagen está corrupta o no se pudo decodificar.');}try{if(bitmap.width!==info.widthPx||bitmap.height!==info.heightPx)throw Error('Dimensiones de imagen incoherentes.');}finally{bitmap.close();}}
 function urlsClear(){for(const entry of urls.values())URL.revokeObjectURL(entry.url);urls.clear();}
 async function cleanup(){try{const live=new Set(library.all().flatMap(e=>(e.project.sourceImages||[]).map(i=>i.storage.ref||i.id)));const keys=await I.keys();await I.remove(keys.filter(k=>!live.has(k)));for(const [key,value]of urls)if(!live.has(key)){URL.revokeObjectURL(value.url);urls.delete(key);}}catch(e){report(Error('El proyecto se guardó; no se pudo limpiar el almacenamiento de imágenes. '+e.message));}}
 function cancel(){clearAssist();mode='navigate';points=[];drawPoints();status('Navegar: arrastra para desplazar; dos dedos o rueda para ampliar. Medidas orientativas.');}
 async function start(next){try{if(is3D())await setView('2d');editing=null;ui.sel=null;setTool('select');mode=next;points=[];closeDrawers();status({wall:'Muro: toca dos extremos. Ajuste opcional a 45°/90°.',room:'Estancia: toca sus vértices y luego pulsa «Cerrar estancia».',calibrate:'Calibrar: toca dos puntos de una cota conocida.',verify:'Verificar: toca dos puntos de una segunda cota independiente.',door:'Puerta: toca un muro. Ancho inicial 800 mm.',window:'Ventana: toca un muro. Ancho inicial 800 mm.',edit:'Editar: toca un muro, hueco o estancia. Usa el panel para modificar o eliminar.'}[next]||'Navegar');drawPoints();}catch(e){report(e);}}
 function drawPoints(){drawAssist();const g=$('#gTrace');g.replaceChildren();for(const p of points){const world=['calibrate','verify'].includes(mode)&&image()?T.imageToWorld(image(),p):p,node=document.createElementNS(svg.namespaceURI,'circle');node.setAttribute('cx',world.x);node.setAttribute('cy',world.y);node.setAttribute('r',8/view.s);node.setAttribute('fill','#b5653a');g.append(node);}if(points.length>1&&['wall','room'].includes(mode)){const n=document.createElementNS(svg.namespaceURI,'polyline');n.setAttribute('points',points.map(p=>`${p.x},${p.y}`).join(' '));n.setAttribute('fill','none');n.setAttribute('stroke','#b5653a');n.setAttribute('stroke-width',2/view.s);g.append(n);}}
 async function drawImages(){const g=$('#gSource');g.replaceChildren();for(const im of project.sourceImages||[]){if(!im.placement||im.visible===false)continue;if(im.storage.kind!=='local-browser'){status('La imagen referenciada no está en este navegador. Importa el ZIP para recuperarla.');continue;}const key=im.storage.ref||im.id;
   if(!urls.has(key)){if(im.storage.kind!=='local-browser'||loading.has(key))continue;loading.add(key);const current=project.id;try{const blob=await I.get(key);if(!blob){status('Imagen local no disponible. Importa su ZIP para recuperarla.');continue;}const bytes=new Uint8Array(await blob.arrayBuffer()),info=T.imageInfo(bytes,im.mediaType);if(info.widthPx!==im.widthPx||info.heightPx!==im.heightPx)throw Error('La imagen local no coincide con las dimensiones de su referencia.');await decode(bytes,info);urls.set(key,{url:URL.createObjectURL(new Blob([T.renderBytes(bytes,info)],{type:info.mediaType}))});queueMicrotask(()=>drawImages());}catch(e){report(e);}finally{loading.delete(key);}continue;}
   const n=document.createElementNS(svg.namespaceURI,'image');n.setAttribute('href',urls.get(key).url);n.setAttribute('width',im.widthPx);n.setAttribute('height',im.heightPx);n.setAttribute('opacity',im.opacity??.55);const pl=im.placement;n.setAttribute('transform',`translate(${pl.originMm.x} ${pl.originMm.y}) rotate(${pl.rotationDeg}) scale(${pl.mmPerPixel})`);g.append(n);
  }}
 function render(){if(lastId!==library?.activeId()||lastRoot!==project.id){lastId=library?.activeId();lastRoot=project.id;operation++;mode='navigate';points=[];editing=null;selectedImage=undefined;urlsClear();status('Navegar: arrastra para desplazar; dos dedos o rueda para ampliar. Medidas orientativas.');}checkAssist();drawImages();drawPoints();$('#scaleConfidence').textContent='Medidas orientativas · escala '+({pending:'pendiente',estimated:'estimada',real:'confirmada por la persona'}[project.scale.confidence]);if(!shown)return;
  const panel=$('#tracePanel');panel.hidden=false;panel.replaceChildren();
  const title=document.createElement('h3');title.textContent='Plano propio · trazado manual';panel.append(title);
  const note=document.createElement('p');note.textContent=`Medidas orientativas · Escala: ${project.scale.confidence==='real'?'confirmada por la persona':project.scale.confidence==='estimated'?'estimada':'pendiente'}`;panel.append(note);const privacy=document.createElement('p');privacy.textContent='El ZIP incluye las imágenes originales y sus metadatos. Revisa sus datos personales antes de compartirlo.';panel.append(privacy);
  const actions=document.createElement('div');actions.className='actions';panel.append(actions);
  for(const [id,text,fn]of [['traceNew','Nuevo desde imagen',()=>openImage(true)],['traceAddImage','Añadir imagen',()=>openImage(false)],['traceCalibrate','Calibrar',()=>start('calibrate')],['traceVerify','Segunda cota',()=>start('verify')],['traceConfirm','Confirmar escala',()=>{try{apply(T.confirm);status('Escala confirmada por la persona. Las medidas siguen siendo orientativas.');}catch(e){report(e);}}],['traceWall','Muro',()=>start('wall')],['traceDoor','Puerta',()=>start('door')],['traceWindow','Ventana',()=>start('window')],['traceRoom','Estancia',()=>start('room')],['traceUndoPoint','Quitar último punto',()=>{points.pop();drawPoints();}],['traceCloseRoom','Cerrar estancia',()=>{try{if(mode!=='room'||points.length<3)throw Error('Marca al menos tres vértices.');const polygon=points;apply(p=>T.room(p,polygon));points=[];drawPoints();status('Estancia guardada. Revisa su contorno.');}catch(e){report(e);}}],['traceEdit','Seleccionar/editar',()=>start('edit')],['traceNavigate','Navegar/cancelar',cancel],['traceExport','Exportar ZIP',async()=>{try{download('proyecto-plano.zip',await P.encode(project,I.get));}catch(e){report(e);}}],['traceImport','Importar ZIP',()=>$('#traceZipFile').click()],['traceHidePanel','Cerrar herramientas',()=>{shown=false;panel.hidden=true;drawer(null);}]] ){
   const b=document.createElement('button');b.id=id;b.className='btn';b.textContent=text;b.onclick=fn;actions.append(b);
  }
  assistPanel(panel);
  const snapLabel=document.createElement('label'),snapInput=document.createElement('input');snapInput.id='traceSnap';snapInput.type='checkbox';snapInput.checked=snapEnabled;snapInput.onchange=()=>snapEnabled=snapInput.checked;snapLabel.append(snapInput,document.createTextNode(' Ajustar extremos y ángulos 45°/90°'));panel.append(snapLabel);
  const c=project.scale.calibration,v=project.scale.verification;if(c){const text=document.createElement('p');text.textContent=`Cota: ${c.knownLengthMm} mm · ${c.mmPerPixel.toFixed(4)} mm/píxel`+(v?` · Segunda cota: ${v.measuredLengthMm}/${v.knownLengthMm} mm · Error ${v.errorPercent.toFixed(2)} % · ${v.status==='consistent'?'concuerda':'revisar'} (aviso provisional: ${v.thresholdPercent} %)`:' · Falta segunda cota');panel.append(text);}
  if(project.sourceImages?.length){const label=document.createElement('label');label.textContent='Imagen de referencia';const selector=document.createElement('select');selector.id='traceImageSelect';for(const im of project.sourceImages){const o=document.createElement('option');o.value=im.id;o.textContent=im.id;selector.append(o);}selector.value=image().id;selector.onchange=()=>{cancel();selectedImage=selector.value;render();};label.append(selector);panel.append(label);
   const im=image();if(!im.placement){const place=document.createElement('button');place.className='btn';place.id='tracePlaceImage';place.textContent='Colocar imagen sin transformación';place.onclick=()=>{try{apply(p=>{p.sourceImages.find(i=>i.id===im.id).placement={originMm:{x:0,y:0},rotationDeg:0,mmPerPixel:10};});fitView();}catch(e){report(e);}};panel.append(place);}
   for(const [id,labelText,type,value,fn]of [['traceVisible','Mostrar imagen','checkbox',im.visible!==false,(p,val)=>p.sourceImages.find(i=>i.id===im.id).visible=val],['traceOpacity','Opacidad (0–1)','number',im.opacity??.55,(p,val)=>p.sourceImages.find(i=>i.id===im.id).opacity=val],['traceImageX','Origen X (mm)','number',im.placement?.originMm.x??0,(p,val)=>p.sourceImages.find(i=>i.id===im.id).placement.originMm.x=val],['traceImageY','Origen Y (mm)','number',im.placement?.originMm.y??0,(p,val)=>p.sourceImages.find(i=>i.id===im.id).placement.originMm.y=val],['traceImageRotation','Giro (−180 a 180°)','number',im.placement?.rotationDeg??0,(p,val)=>p.sourceImages.find(i=>i.id===im.id).placement.rotationDeg=val]]){
    const l=document.createElement('label');l.textContent=labelText;const input=document.createElement('input');input.id=id;input.type=type;if(type==='checkbox')input.checked=value;else{input.value=value;input.step=id==='traceOpacity'?'.05':'1';}input.onchange=()=>{try{apply(p=>{if(id.startsWith('traceImage'))p.sourceImages.find(i=>i.id===im.id).placement??={originMm:{x:0,y:0},rotationDeg:0,mmPerPixel:10};fn(p,type==='checkbox'?input.checked:Number(input.value));});}catch(e){report(e);render();}};l.append(input);panel.append(l);
   }
   const del=document.createElement('button');del.className='btn danger';del.id='traceRemoveImage';del.textContent='Eliminar imagen';del.onclick=async()=>{if(!confirm('¿Eliminar la imagen de referencia? La geometría se conserva; exporta el ZIP antes si necesitas una copia.'))return;try{apply(p=>{p.sourceImages=p.sourceImages.filter(i=>i.id!==im.id);if(p.scale.calibration?.sourceImageId===im.id)p.scale={confidence:'pending',method:'none'};});undoStack.length=redoStack.length=0;await cleanup();}catch(e){report(e);}};panel.append(del);
  }
  const warnings=document.createElement('div');warnings.id='traceWarnings';warnings.setAttribute('aria-label','Avisos de revisión');for(const w of T.warnings(project)){const b=document.createElement('button');b.className='btn';b.textContent=`${w.code} · ${w.id}: ${w.message}`;b.onclick=()=>locate(w.id);warnings.append(b);}if(!warnings.childNodes.length)warnings.textContent='Sin avisos W1–W4. Las medidas siguen siendo orientativas.';panel.append(warnings);
 }
 function focusPoint(point){view.x0=point.x-svg.clientWidth/2/view.s;view.y0=point.y-svg.clientHeight/2/view.s;applyView();drawPoints();}
 function locate(id){const groups=[['wall',project.walls],['opening',project.openings],['room',project.rooms]];for(const [kind,list]of groups)if(list.some(e=>e.id===id)){editing={kind,id};ui.sel=null;renderPanel();drawer('panel',true);const e=list.find(e=>e.id===id);const w=kind==='opening'?project.walls.find(w=>w.id===e.wallId):e;const point=kind==='room'?{x:e.polygon.reduce((n,p)=>n+p.x,0)/e.polygon.length,y:e.polygon.reduce((n,p)=>n+p.y,0)/e.polygon.length}:kind==='opening'?{x:w.start.x+(w.end.x-w.start.x)*(e.offsetMm+e.widthMm/2)/Math.hypot(w.end.x-w.start.x,w.end.y-w.start.y),y:w.start.y+(w.end.y-w.start.y)*(e.offsetMm+e.widthMm/2)/Math.hypot(w.end.x-w.start.x,w.end.y-w.start.y)}:{x:(w.start.x+w.end.x)/2,y:(w.start.y+w.end.y)/2};focusPoint(point);return;}const obj=project.objects.find(o=>o.id===id);if(obj){select({kind:'furn',id});drawer('panel',true);focusPoint(obj.position);}else toast('Revisa la calibración y la segunda cota.',5000);}
 function editPanel(){if(!editing)return false;const {kind,id}=editing,e=(kind==='wall'?project.walls:kind==='opening'?project.openings:project.rooms).find(e=>e.id===id);if(!e){editing=null;return false;}const panel=$('#panel');panel.replaceChildren();const title=document.createElement('h3');title.textContent=`Editar ${kind==='wall'?'muro':kind==='opening'?'hueco':'estancia'} · ${id}`;panel.append(title);
  const fields=kind==='wall'?[['start.x','Inicio X (mm)'],['start.y','Inicio Y (mm)'],['end.x','Fin X (mm)'],['end.y','Fin Y (mm)'],['thicknessMm','Grosor (mm)'],['heightMm','Altura (mm)']]:kind==='opening'?[['offsetMm','Distancia desde inicio del muro (mm)'],['widthMm','Ancho (mm)'],['heightMm','Altura (mm)'],['sillHeightMm','Antepecho (mm)']]:[['name','Nombre de estancia']];
  const form=document.createElement('form');panel.append(form);const inputs=[];for(const [path,text]of fields){const label=document.createElement('label');label.textContent=text;label.style.display='block';const input=document.createElement('input');input.id='traceEdit-'+path.replace('.','-');input.type=path==='name'?'text':'number';input.required=true;input.style.width='100%';input.style.padding='8px';input.style.fontSize='16px';input.value=path.split('.').reduce((o,k)=>o[k],e);label.append(input);form.append(label);inputs.push([path,input]);}
  let polygon;if(kind==='room'){const label=document.createElement('label');label.textContent='Vértices X,Y en mm (uno por línea)';polygon=document.createElement('textarea');polygon.id='traceEditPolygon';polygon.style.width='100%';polygon.rows=6;polygon.value=e.polygon.map(p=>`${p.x},${p.y}`).join('\n');label.append(polygon);form.append(label);}
  const saveButton=document.createElement('button');saveButton.className='btn primary';saveButton.textContent='Guardar geometría';saveButton.id='traceEditSave';form.append(saveButton);
  form.onsubmit=event=>{event.preventDefault();try{apply(p=>{const target=(kind==='wall'?p.walls:kind==='opening'?p.openings:p.rooms).find(x=>x.id===id);for(const [path,input]of inputs){const keys=path.split('.'),owner=keys.length===2?target[keys[0]]:target;owner[keys.at(-1)]=path==='name'?input.value:Number(input.value);}if(polygon)target.polygon=polygon.value.split('\n').filter(l=>l.trim()).map(l=>{const a=l.split(',').map(Number);if(a.length!==2)throw Error('Cada vértice requiere X,Y.');return {x:a[0],y:a[1]};});target.source={method:target.source?.method==='suggested'?'suggested':'manual',review:'unreviewed'};});status('Geometría actualizada; revisa los avisos.');}catch(e){report(e);}};
  for(const [id,text,fn]of [['traceReviewed','Confirmar revisión de este elemento',()=>apply(p=>{const target=(kind==='wall'?p.walls:kind==='opening'?p.openings:p.rooms).find(e=>e.id===editing.id);target.source={method:target.source?.method||'manual',review:'confirmed'};})],['traceDeleteGeometry','Eliminar elemento',()=>{if(confirm('¿Eliminar este elemento? Al borrar un muro se eliminan también sus huecos.')){const target=editing;editing=null;apply(p=>T.remove(p,target.kind,target.id));}}],['traceEditBack','Volver',()=>{editing=null;renderPanel();}]]){const b=document.createElement('button');b.id=id;b.className='btn';b.textContent=text;b.onclick=()=>{try{fn();}catch(e){report(e);}};panel.append(b);}return true;
 }
 let snapEnabled=true,newImage=true,newProjectName='Plano desde imagen';
 $('#traceBtn').onclick=()=>{shown=true;render();drawer('panel',true);};
 let tapping=null;
 // Capture only intentional drawing taps. Dragging in a trace mode never creates geometry.
 svg.addEventListener('pointerdown',e=>{if(mode==='navigate')return;if(e.button!==0)return;closeDrawers();if(tapping){tapping.cancel=true;e.stopImmediatePropagation();return;}tapping={id:e.pointerId,x:e.clientX,y:e.clientY,cancel:false};svg.setPointerCapture(e.pointerId);e.stopImmediatePropagation();},true);
 svg.addEventListener('pointermove',e=>{if(!tapping)return;if(Math.hypot(e.clientX-tapping.x,e.clientY-tapping.y)>10)tapping.cancel=true;e.stopImmediatePropagation();},true);
 svg.addEventListener('pointerup',e=>{if(!tapping||tapping.id!==e.pointerId)return;const tap=tapping;tapping=null;e.stopImmediatePropagation();if(tap.cancel)return;try{const world=toMM(e);
   if(['calibrate','verify'].includes(mode)){const im=image();if(!im?.placement)throw Error('Importa y selecciona una imagen primero.');points.push(T.worldToImage(im,world));if(points.length===2){distanceMode=mode;$('#traceKnown').value='';$('#traceDistanceError').textContent='';$('#tracePoints').textContent=points.map(p=>`(${p.x.toFixed(2)}, ${p.y.toFixed(2)}) px originales`).join(' → ');$('#traceDistance').showModal();$('#traceKnown').focus();}drawPoints();}
   else if(mode==='wall'||mode==='room'){if(mode==='room'&&points.length>=200)throw Error('Máximo 200 vértices por estancia.');const q=T.snap(world,points.at(-1),project.walls,snapEnabled,10/view.s);points.push(q);if(mode==='wall'&&points.length===2){const [a,b]=points;apply(p=>T.wall(p,a,b));points=[];status('Muro guardado. Toca otros dos extremos o elige Navegar.');}drawPoints();}
   else if(mode==='door'||mode==='window'){const closest=project.walls.filter(w=>w.status!=='demolished').map(w=>({w,d:T.segmentPoint(world,w.start,w.end).distance})).sort((a,b)=>a.d-b.d)[0];if(!closest||closest.d>Math.max(closest.w.thicknessMm/2,16/view.s))throw Error('Toca cerca del muro que debe contener el hueco.');apply(p=>T.opening(p,closest.w.id,world,mode));status('Hueco creado. Seleccionar/editar permite ajustar sus medidas.');}
   else if(mode==='edit'){const opened=project.openings.map(o=>{const w=project.walls.find(w=>w.id===o.wallId),L=T.segmentPoint(world,w.start,w.end).t*T_SEG_LENGTH(w);return {o,w,L,d:T.segmentPoint(world,w.start,w.end).distance};}).find(x=>x.L>=x.o.offsetMm&&x.L<=x.o.offsetMm+x.o.widthMm&&x.d<=Math.max(x.w.thicknessMm/2,12/view.s));if(opened)locate(opened.o.id);else{const nearest=project.walls.map(w=>({w,d:T.segmentPoint(world,w.start,w.end).distance})).sort((a,b)=>a.d-b.d)[0];if(nearest&&nearest.d<=Math.max(nearest.w.thicknessMm/2,12/view.s))locate(nearest.w.id);else{const hit=e.target.closest('[data-room]');if(hit)locate(hit.dataset.room);else toast('No hay geometría en este punto.');}}}
  }catch(e){points=[];drawPoints();report(e);}},true);
 const T_SEG_LENGTH=w=>Math.hypot(w.end.x-w.start.x,w.end.y-w.start.y);
 svg.addEventListener('pointercancel',()=>{tapping=null;},true);
 $('#traceDistanceCancel').onclick=()=>{points=[];drawPoints();$('#traceDistance').close();};$('#traceDistance').addEventListener('cancel',()=>{points=[];drawPoints();});
 $('#traceDistanceSave').onclick=()=>{try{const captured=points,im=image();apply(p=>distanceMode==='calibrate'?T.calibrate(p,im.id,captured[0],captured[1],Number($('#traceKnown').value)):T.verify(p,captured[0],captured[1],Number($('#traceKnown').value)));points=[];mode='navigate';$('#traceDistance').close();drawPoints();render();status(distanceMode==='calibrate'?'Calibración guardada. Introduce una segunda cota independiente. La geometría en mm se conserva; revisa su correspondencia con la imagen.':'Segunda cota guardada. Revisa el error antes de confirmar la escala.');drawer('panel',true);}catch(e){$('#traceDistanceError').textContent=e.message;}};
 function openImage(createNew=true,name='Plano desde imagen'){newImage=createNew;newProjectName=name;$('#traceImageFile').click();}
 $('#importImage').onclick=()=>{document.querySelector('details.menu').open=false;openImage(true);};
 async function addImage(file,createNew,name=newProjectName){const serial=++operation,current=project.id,initial=snap();let buffer;try{buffer=await file.arrayBuffer();}catch{throw Error('No se pudo leer la imagen. Vuelve a seleccionarla desde el dispositivo.');}const bytes=new Uint8Array(buffer),info=T.imageInfo(bytes,file.type,file.name);const rotation=T.orientationAngle(info);if(rotation===undefined)throw Error('El JPEG tiene orientación EXIF reflejada. Exporta una copia PNG con la orientación aplicada antes de importarlo.');await decode(bytes,info);const sha=await P.digest(bytes);if(serial!==operation||current!==project.id||snap()!==initial)return;
  const next=createNew?T.blank(name):Core.clone(project);if((next.sourceImages||[]).length>=20)throw Error('Máximo 20 imágenes por proyecto.');if(Number(next.schemaVersion.split('.')[1])<2)next.schemaVersion=info.mediaType==='image/webp'?'1.2.0':'1.1.0';const key=Core.id('img'),im={id:Core.id('img'),mediaType:info.mediaType,widthPx:info.widthPx,heightPx:info.heightPx,bytes:bytes.length,sha256:sha,storage:{kind:'local-browser',ref:key},placement:{originMm:{x:0,y:0},rotationDeg:rotation,mmPerPixel:10},visible:true,opacity:.55};(next.sourceImages||=[]).push(im);Core.validate(next);await I.put([[key,new Blob([bytes],{type:info.mediaType})]]);
  try{if(serial!==operation||current!==project.id||snap()!==initial){await I.remove([key]);return;}if(createNew){project=library.add(next,name);undoStack.length=redoStack.length=0;ui.sel=null;editing=null;}else{apply(p=>{p.schemaVersion=next.schemaVersion;(p.sourceImages||=[]).push(im);});}selectedImage=im.id;refreshProject();renderAll();fitView();shown=true;render();drawer('panel',true);status('Imagen local preparada. Calibra antes de trazar; medidas orientativas.');}catch(e){await I.remove([key]);throw e;}
 }
 $('#traceImageFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>T.LIMITS.bytes)throw Error('La imagen supera 15 MiB.');await addImage(file,newImage);}catch(err){report(err);}};
 async function importZip(file){if(file.size>T.LIMITS.packageBytes)throw Error('El ZIP supera 320 MB.');const serial=++operation,current=project.id,initial=snap(),entries=await P.unzip(await file.arrayBuffer()),result=await P.validateEntries(entries,decode),pending=[];
  for(const {image,bytes}of result.images){const key=Core.id('img');image.storage={kind:'local-browser',ref:key};pending.push([key,new Blob([bytes],{type:image.mediaType})]);}Core.validate(result.project);if(serial!==operation||current!==project.id||snap()!==initial)return;
  await I.put(pending);try{if(serial!==operation||current!==project.id||snap()!==initial){await I.remove(pending.map(e=>e[0]));return;}project=library.add(result.project,'Proyecto ZIP importado');editing=null;ui.sel=null;undoStack.length=redoStack.length=0;refreshProject();shown=true;renderAll();fitView();status('ZIP importado localmente. Revisa la escala y los avisos.');}catch(e){await I.remove(pending.map(e=>e[0]));throw e;}
 }
 $('#traceZipFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(file)try{await importZip(file);}catch(err){report(err);}};
 addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#traceDistance').open&&!rawDialog.open){cancel();editing=null;renderPanel();}});
 window.FloorPlanTraceUI={openImage,render,editPanel,cancel,cleanup,decode,importZip,viewChanged};render();
})();
