const {test,before,after}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs/promises'),path=require('node:path'),{createServer}=require('node:http'),{chromium}=require('playwright');
const {execFile}=require('node:child_process'),{promisify}=require('node:util'),run=promisify(execFile);
const L=require('../js/room-layout.js'),Core=require('../js/project-core.js'),T=require('../js/tracing-core.js');
let server,browser,url;const cache=new Map();
before(async()=>{const root=path.resolve(__dirname,'..');server=createServer(async(req,res)=>{try{const file=path.resolve(root,'.'+(req.url==='/'?'/index.html':new URL(req.url,'http://local').pathname));if(!file.startsWith(root+path.sep))throw Error('path');res.setHeader('Content-Type',file.endsWith('.js')||file.endsWith('.mjs')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.webp')?'image/webp':file.endsWith('.json')?'application/json':'text/html');res.end(await fs.readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));url=`http://127.0.0.1:${server.address().port}/`;browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});});
after(async()=>{await browser?.close();await new Promise(r=>server?.close(r));});
async function setup(t,viewport={width:1440,height:900},webgl=true){const mobile=viewport.width<1000,context=await browser.newContext({viewport,isMobile:mobile,hasTouch:mobile,acceptDownloads:true});t.after(()=>context.close());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://cdn.jsdelivr.net/npm/three@0.160.0/**',async route=>{if(!webgl)return route.abort();const target=route.request().url();let p=cache.get(target);if(!p){p=run('curl',['--fail','--silent','--show-error','--max-time','20',target],{maxBuffer:4*1024*1024}).then(r=>r.stdout);cache.set(target,p);}await route.fulfill({contentType:'text/javascript',headers:{'access-control-allow-origin':'*'},body:await p});});
 await page.goto(url);if(webgl)await page.waitForFunction(()=>window.View3D);return {page,errors};}
async function click(page,id){const b=page.locator(id);await b.scrollIntoViewIfNeeded();if(await page.evaluate(()=>matchMedia('(pointer:coarse)').matches))await b.tap();else await b.click();}
async function confirm(page){await click(page,'#roomDesignReview');assert.equal(await page.locator('#roomDesignError').textContent(),'');await click(page,'#roomDesignConfirm');}
async function rooms(page){return page.evaluate(()=>structuredClone(FloorPlanApp.project));}
async function exportFile(page,selector){await page.locator('details.menu summary').click();const pending=page.waitForEvent('download');await page.locator(selector).click();const dl=await pending,s=await dl.createReadStream(),chunks=[];for await(const c of s)chunks.push(c);return Buffer.concat(chunks);}
for(const viewport of [{width:1440,height:900},{width:390,height:844},{width:844,height:390}])test(`new home / room dimensions / history / software 3D ${viewport.width}x${viewport.height}`,{timeout:120000},async t=>{
 const {page,errors}=await setup(t,viewport),original=await rooms(page);
 await click(page,'#newProjectBtn');await page.fill('#newProjectName','Casa vacía');await click(page,'#newProjectBlank');assert.equal((await rooms(page)).rooms.length,0);assert.equal(await page.locator('#roomDesignTitle').textContent(),'Nueva estancia');
 await page.fill('#roomDesignName','Salón');await confirm(page);const first=await rooms(page),id=first.rooms[0].id;assert.equal(first.walls.length,4);assert.equal(first.name,'Casa vacía');assert.ok(await page.locator('#gLabels').textContent().then(t=>t.includes('3000 × 4000 mm')));
 await click(page,'#newRoomBtn');await page.fill('#roomDesignName','Cocina');await page.selectOption('#roomDesignPlacement',id+':right');await page.fill('#roomDesignWidth','2500');await confirm(page);const two=await rooms(page),kitchen=two.rooms[1].id;assert.equal(two.walls.length,7);
 // Main properties retain the selected room and launch actual numeric editing.
 await click(page,'#roomDimensions');await page.fill('#roomDesignValue','2800');await page.selectOption('#roomDesignFixed','left');await click(page,'#roomDesignReview');assert.deepEqual(await rooms(page),two);assert.equal(await page.locator('#roomDesignSvg').count(),1);await fs.mkdir('docs/qa/artifacts/home-room-dimensions',{recursive:true});await page.screenshot({path:`docs/qa/artifacts/home-room-dimensions/${viewport.width}x${viewport.height}-preview.png`});await click(page,'#roomDesignCancel');assert.deepEqual(await rooms(page),two);
 await click(page,'#roomDimensions');await page.fill('#roomDesignValue','2800');await page.selectOption('#roomDesignFixed','left');await confirm(page);const resized=await rooms(page);assert.equal(L.rectangle(resized.rooms[1]).width,2800);assert.deepEqual(resized.rooms[0],two.rooms[0]);
 await click(page,'#undo');assert.deepEqual(await rooms(page),two);await click(page,'#redo');assert.deepEqual(await rooms(page),resized);
 // Shared-wall rejection remains visible and atomic.
 await click(page,'#roomDimensions');await page.fill('#roomDesignValue','3000');await page.selectOption('#roomDesignFixed','right');await click(page,'#roomDesignReview');assert.match(await page.locator('#roomDesignError').textContent(),/vecina/);assert.equal(await page.locator('#roomDesignConfirm').isDisabled(),true);assert.deepEqual(await rooms(page),resized);await click(page,'#roomDesignCancel');
 if(viewport.width<1000)await page.evaluate(()=>{document.querySelector('aside.right').classList.remove('open');document.querySelector('aside.lib').classList.remove('open');});
 await click(page,'[data-view="3d"]');await page.waitForFunction(()=>document.querySelector('#stage').classList.contains('is3d')&&!document.body.classList.contains('busy'));
 assert.ok(await page.evaluate(()=>View3D.renderedSource===FloorPlanApp.project&&View3D.renderedGeometry===FloorPlanApp.geometry&&FloorPlanApp.source2D===FloorPlanApp.project));assert.ok(await page.locator('#view3d canvas').count());
 const metrics=await page.evaluate(()=>({canvas:document.querySelector('#view3d canvas').clientHeight,stage:document.querySelector('#stage').clientHeight,walls:View3D.wallMeshes}));assert.ok(metrics.canvas>=metrics.stage*.6);assert.equal(new Set(metrics.walls.map(w=>w.id)).size,7);
 await fs.mkdir('docs/qa/artifacts/home-room-dimensions',{recursive:true});await page.screenshot({path:`docs/qa/artifacts/home-room-dimensions/${viewport.width}x${viewport.height}-3d.png`});
 await click(page,'[data-view="2d"]');await page.waitForFunction(()=>!document.body.classList.contains('busy'));await page.reload();assert.deepEqual(await rooms(page),resized);
 const json=JSON.parse((await exportFile(page,'#exportJson')).toString());assert.deepEqual(json,resized);
 // Existing raster flow with a requested project name; old project is preserved.
 await click(page,'#newProjectBtn');await page.fill('#newProjectName','Casa imagen');await click(page,'#newProjectImage');await page.locator('#traceImageFile').setInputFiles('tests/fixtures/manual-plan.webp');await page.waitForFunction(()=>FloorPlanApp.project.name==='Casa imagen'&&FloorPlanApp.project.sourceImages.length===1);const image=await rooms(page);assert.equal(image.rooms.length,0);assert.notEqual(image.id,resized.id);
 const imageHash=image.sourceImages[0].sha256;
 await page.evaluate(()=>{const im=FloorPlanApp.project.sourceImages[0];const p=structuredClone(FloorPlanApp.project);FloorPlanTracing.calibrate(p,im.id,{x:0,y:0},{x:1,y:0},100);FloorPlanApp.importProject(p);});
 await click(page,'#newRoomBtn');await page.fill('#roomDesignName','Imagen estancia');await confirm(page);const fromImage=await rooms(page);assert.equal(fromImage.sourceImages[0].sha256,imageHash);assert.equal(fromImage.scale.calibration.knownLengthMm,100);
 const packageFile=await page.evaluate(async()=>{const blob=await FloorPlanPackage.encode(FloorPlanApp.project,key=>FloorPlanImages.get(key));return Array.from(new Uint8Array(await blob.arrayBuffer()));});await page.locator('#traceZipFile').setInputFiles({name:'house.zip',mimeType:'application/zip',buffer:Buffer.from(packageFile)});await page.waitForFunction(()=>document.querySelector('#traceStatus').textContent.includes('ZIP importado'));assert.equal((await rooms(page)).rooms[0].id,fromImage.rooms[0].id);assert.equal((await rooms(page)).sourceImages[0].sha256,imageHash);
 await click(page,'#projectsBtn');const list=await page.locator('#projectList option').evaluateAll(ns=>ns.map(n=>({id:n.value,name:n.textContent})));const old=list.find(n=>n.name==='Casa vacía');assert.ok(old);await page.selectOption('#projectList',old.id);await click(page,'#projectOpen');assert.deepEqual(await rooms(page),resized);assert.ok(list.some(n=>n.name!=='Casa vacía'&&n.name!=='Casa imagen'));assert.notEqual(original.id,resized.id);
 if(viewport.width<1000)await page.evaluate(()=>document.querySelector('aside.right').classList.remove('open'));
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`docs/qa/artifacts/home-room-dimensions/${viewport.width}x${viewport.height}-2d.png`});assert.deepEqual(errors,[]);const commit=(await run('git',['rev-parse','HEAD'])).stdout.trim();await fs.writeFile(`docs/qa/artifacts/home-room-dimensions/${viewport.width}x${viewport.height}-metrics.json`,JSON.stringify({commitAtRun:commit,viewport,input:viewport.width<1000?'touch taps':'mouse clicks',rendering:'Chromium SwiftShader software',canvasHeight:metrics.canvas,stageHeight:metrics.stage,wallMeshes:metrics.walls,rooms:resized.rooms,checks:['independent projects','shared wall','numeric preview cancel','confirm undo redo','reload','JSON export','image calibration preserved','ZIP round trip','same canonical 2D and 3D source'],pageErrors:errors},null,2)+'\n');t.diagnostic('3D: Chromium SwiftShader software; no physical mobile performance claim.');
});
test('cancel project dialog, image rejection and persistence failure preserve prior project',{timeout:60000},async t=>{const {page}=await setup(t,{width:390,height:844},false),before=await rooms(page);await click(page,'#newProjectBtn');await page.fill('#newProjectName','No creada');await click(page,'#roomDesignCancel');assert.deepEqual(await rooms(page),before);await click(page,'#newProjectBtn');await click(page,'#newProjectImage');await page.locator('#traceImageFile').setInputFiles({name:'invalid.png',mimeType:'image/png',buffer:Buffer.from('invalid')});await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('Solo se admiten'));assert.deepEqual(await rooms(page),before);
 await click(page,'#newProjectBtn');await click(page,'#newProjectBlank');await click(page,'#roomDesignCancel');const blank=await rooms(page);await click(page,'#newRoomBtn');await click(page,'#roomDesignReview');assert.equal(await page.locator('#roomDesignError').textContent(),'');await page.evaluate(()=>Storage.prototype.setItem=()=>{throw Error('quota QA');});await click(page,'#roomDesignConfirm');assert.match(await page.locator('#roomDesignError').textContent(),/quota QA/);assert.deepEqual(await rooms(page),blank);});
test('moving door/window consent is explicit, cancellation and one-step history preserve IDs',{timeout:60000},async t=>{const {page,errors}=await setup(t,{width:390,height:844},false),a=L.create(L.blank('Huecos'),{name:'Salón',width:3000,depth:4000}),w=L.mapping(a.project,a.project.rooms[0]).find(s=>s.key==='right').wall;T.opening(a.project,w.id,{x:w.start.x,y:1000},'door');T.opening(a.project,w.id,{x:w.start.x,y:2800},'window',500);await page.evaluate(p=>FloorPlanApp.importProject(p),a.project);
 await page.evaluate(id=>FloorPlanRoomUI.dimensions(id),a.roomId);await page.fill('#roomDesignValue','3500');await page.selectOption('#roomDesignFixed','left');await click(page,'#roomDesignReview');await click(page,'#roomDesignConfirm');assert.match(await page.locator('#roomDesignError').textContent(),/Confirma explícitamente/);assert.deepEqual(await rooms(page),a.project);await page.locator('#roomDesignConsent').check();await click(page,'#roomDesignConfirm');const after=await rooms(page);assert.deepEqual(after.openings,a.project.openings);assert.equal(L.rectangle(after.rooms[0]).width,3500);await click(page,'#undo');assert.deepEqual(await rooms(page),a.project);await click(page,'#redo');assert.deepEqual(await rooms(page),after);assert.deepEqual(errors,[]);});
