const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../js/project-core.js'),T=require('../js/tracing-core.js'),L=require('../js/room-layout.js'),Library=require('../js/project-library.js'),P=require('../js/project-package.js');
function room(){return L.create(L.blank('Casa'),{name:'Salón',width:3000,depth:4000});}
function resize(a,extra={}){return L.resize(a.project,{roomId:a.roomId,axis:'width',value:3500,fixed:'left',...extra});}
function unchanged(a,fn,pattern){const before=JSON.stringify(a.project);assert.throws(fn,pattern);assert.equal(JSON.stringify(a.project),before);}
test('blank project uses unchanged 1.3 contract and independent empty geometry',()=>{const a=L.blank('Uno'),b=L.blank('Dos');C.validate(a);assert.equal(a.schemaVersion,'1.3.0');assert.notEqual(a.id,b.id);for(const k of ['walls','rooms','objects','openings','sourceImages','measurements'])assert.equal(a[k].length,0);});
test('multiple rooms share exactly one complete wall without changing the neighbor',()=>{const a=room(),before=C.clone(a.project),b=L.create(a.project,{name:'Cocina',width:2500,depth:4000,neighborId:a.roomId,side:'right'});assert.equal(b.project.walls.length,7);assert.deepEqual(a.project,before);assert.deepEqual(b.project.rooms[0],before.rooms[0]);assert.deepEqual(b.project.walls.slice(0,4),before.walls);assert.equal(L.rectangle(b.project.rooms[1]).width,2500);const c=L.create(b.project,{name:'Dormitorio',width:3000,depth:2800,neighborId:a.roomId,side:'bottom'});assert.equal(c.project.rooms.length,3);assert.equal(c.project.walls.length,10);});
test('interior dimensions move three walls, preserve IDs, materials, scale and undo snapshot',()=>{const a=room(),before=C.clone(a.project),b=resize(a);assert.deepEqual(a.project,before);assert.equal(L.rectangle(b.project.rooms[0]).width,3500);assert.equal(b.project.rooms[0].id,a.roomId);assert.deepEqual(b.project.walls.map(w=>w.id),a.project.walls.map(w=>w.id));assert.deepEqual(b.project.materials,a.project.materials);assert.deepEqual(b.project.scale,a.project.scale);assert.equal(b.project.rooms[0].polygon[0].x,0);});
test('right/bottom fixed sides and depth changes preserve the selected interior face',()=>{const a=room(),b=resize(a,{fixed:'right',value:2500}),c=resize(a,{axis:'depth',value:4500,fixed:'bottom'});assert.equal(L.rectangle(b.project.rooms[0]).right,3000);assert.equal(L.rectangle(b.project.rooms[0]).x,500);assert.equal(L.rectangle(c.project.rooms[0]).bottom,4000);assert.equal(L.rectangle(c.project.rooms[0]).y,-500);});
test('shared wall stays fixed, moving it or changing its length is rejected atomically',()=>{const a=room(),b=L.create(a.project,{name:'Vecina',width:2500,depth:4000,neighborId:a.roomId});const c=resize(b);assert.deepEqual(c.project.rooms[0],b.project.rooms[0]);assert.deepEqual(c.project.walls.slice(0,4),b.project.walls.slice(0,4));unchanged(b,()=>resize(b,{fixed:'right'}),/vecina/i);unchanged(b,()=>resize(b,{axis:'depth',value:4500,fixed:'top'}),/vecina/i);});
test('door/window on a moving wall require explicit impact; IDs and offsets preserved',()=>{const a=room(),w=L.mapping(a.project,a.project.rooms[0]).find(s=>s.key==='right').wall;T.opening(a.project,w.id,{x:w.start.x,y:1000},'door');T.opening(a.project,w.id,{x:w.start.x,y:2600},'window',500);const b=resize(a);assert.equal(b.requiresOpenings,true);assert.deepEqual(b.project.openings,a.project.openings);assert.match(b.impact.join(' '),/Puerta.*Ventana/);});
test('opening offset changes keep its physical position when the wall start moves',()=>{const a=room(),w=L.mapping(a.project,a.project.rooms[0]).find(s=>s.key==='top').wall;const o=T.opening(a.project,w.id,{x:1900,y:w.start.y},'window',500),b=resize(a,{fixed:'right',value:2500});assert.equal(b.project.openings[0].offsetMm,o.offsetMm-500);assert.equal(b.project.walls.find(q=>q.id===w.id).start.x+b.project.openings[0].offsetMm,w.start.x+o.offsetMm);});
test('openings beyond shortened wall prevent application',()=>{const a=room(),w=L.mapping(a.project,a.project.rooms[0]).find(s=>s.key==='top').wall;T.opening(a.project,w.id,{x:2800,y:w.start.y},'window',800);unchanged(a,()=>resize(a,{value:1500}),/hueco.*fuera/i);});
test('affected manual measurements block, unrelated measurements remain exact',()=>{const a=room();a.project.measurements=[{id:'msr_test',a:{x:0,y:0},b:{x:3000,y:0}}];unchanged(a,()=>resize(a),/cota.*desactualizada/i);a.project.measurements=[{id:'msr_test',a:{x:100,y:100},b:{x:600,y:100}}];assert.deepEqual(resize(a).project.measurements,a.project.measurements);});
test('furniture is never silently moved/scaled/reassigned; shrink or wall collision blocks',()=>{const a=room();a.project.objects.push({...C.object('desk','Mesa',2500,2000,800,600,30,'#aaaaaa'),roomId:a.roomId});unchanged(a,()=>resize(a,{value:2000}),/mueble/i);assert.deepEqual(resize(a).project.objects,a.project.objects);const b=room();b.project.objects.push(C.object('desk','Fuera',3500,2000,500,500,0,'#aaaaaa'));unchanged(b,()=>resize(b),/colisionaría.*mueble/i);});
test('irregular rooms, missing/duplicate walls and junctions refuse safe numeric edit',()=>{const a=room();a.project.rooms[0].polygon[1].y=100;unchanged(a,()=>resize(a),/irregular|diagonal/);const b=room();b.project.walls.pop();unchanged(b,()=>resize(b),/único muro/);const c=room();c.project.walls.push({...C.clone(c.project.walls[0]),id:'wal_duplicate'});unchanged(c,()=>resize(c),/único muro/);const d=room(),w=L.mapping(d.project,d.project.rooms[0]).find(s=>s.key==='right').wall;T.wall(d.project,w.start,{x:w.start.x+1500,y:w.start.y});unchanged(d,()=>resize(d),/conectada/);});
test('creation refuses overlapping rooms, invalid dimensions and mismatched shared spans',()=>{const a=room();unchanged(a,()=>L.create(a.project,{name:'Otra',width:1000,depth:1000,x:500,y:500}),/invadiría/);unchanged(a,()=>L.create(a.project,{name:'Otra',width:2000,depth:3000,neighborId:a.roomId}),/coincidir/);unchanged(a,()=>resize(a,{value:0}),/dimensiones/);});
test('extension fields survive room design and JSON/ZIP round trip',async()=>{const a=room();a.project.extensions={'x-test':{source:'kept'}};const b=resize(a),json=C.prepare(JSON.stringify(b.project)).project;assert.deepEqual(json,b.project);const zip=P.zip(new Map([['project.json',new TextEncoder().encode(JSON.stringify(json))]])),entries=await P.unzip(await zip.arrayBuffer());const validated=await P.validateEntries(entries);assert.deepEqual(validated.project,b.project);});
test('separate projects persist after reload; failed collection write preserves prior data',()=>{const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)},lib=Library.load(storage,C.initial());lib.save(C.initial());const first=lib.activeId(),a=room();lib.add(a.project,'Casa');const second=lib.activeId();lib.save(resize(a).project);lib.add(L.blank('Otra'),'Otra');const again=Library.load(storage,C.initial());again.open(first);assert.equal(again.project().rooms.length,13);again.open(second);assert.equal(L.rectangle(again.project().rooms[0]).width,3500);const before=map.get(Library.KEY);storage.setItem=()=>{throw Error('quota');};assert.throws(()=>again.save(resize(a).project),/quota/);assert.equal(map.get(Library.KEY),before);});
test('prolonged walls and partial/irregular neighbors cannot be silently displaced',()=>{const a=room(),w=L.mapping(a.project,a.project.rooms[0]).find(s=>s.key==='right').wall;w.end.y+=1000;unchanged(a,()=>resize(a),/prolonga/);const b=room();T.room(b.project,[{x:3240,y:0},{x:5240,y:0},{x:5240,y:2000},{x:4240,y:3000},{x:3240,y:2000}],'Irregular vecina');unchanged(b,()=>resize(b,{value:2500}),/vecina/);});
test('measurements anchored at wall axes also refuse dimensional changes',()=>{const a=room(),w=L.mapping(a.project,a.project.rooms[0]).find(s=>s.key==='right').wall;a.project.measurements=[{id:'msr_axis',a:{x:w.start.x,y:1000},b:{x:w.start.x,y:2000}}];unchanged(a,()=>resize(a),/cota/);});
