const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{createServer}=require('node:http'),{chromium}=require('playwright');
const {execFile}=require('node:child_process'),run=require('node:util').promisify(execFile),entries=require('../assets/materials/catalog.json').entries;
let browser,server,url;const cache=new Map(),QA='docs/qa/artifacts/surface-library';
before(async()=>{const root=path.resolve(__dirname,'..');server=createServer(async(req,res)=>{try{const f=path.resolve(root,'.'+(req.url==='/'?'/index.html':new URL(req.url,'http://local').pathname));if(!f.startsWith(root+path.sep))throw Error('path');res.setHeader('Content-Type',/\.m?js$/.test(f)?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.webp')?'image/webp':f.endsWith('.json')?'application/json':'text/html');res.end(await fs.readFile(f));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));url=`http://127.0.0.1:${server.address().port}/`;browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});await fs.mkdir(QA,{recursive:true});});
after(async()=>{await browser?.close();await new Promise(r=>server?.close(r));});
async function setup(t,viewport={width:1440,height:900}){const context=await browser.newContext({viewport,isMobile:viewport.width<1000,hasTouch:viewport.width<1000,acceptDownloads:true});t.after(()=>context.close());const page=await context.newPage(),errors=[],maps=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(/assets\/materials\/.*\.webp/.test(r.url()))maps.push(r.url());});
 await page.route('https://cdn.jsdelivr.net/npm/three@0.160.0/**',async route=>{const u=route.request().url();if(!cache.has(u))cache.set(u,run('curl',['--fail','--silent','--show-error','--max-time','20',u],{maxBuffer:4*1024*1024}).then(r=>r.stdout));await route.fulfill({contentType:'text/javascript',headers:{'access-control-allow-origin':'*'},body:await cache.get(u)});});
 await page.goto(url);await page.waitForFunction(()=>window.View3D&&FloorPlanSurfaces.entries.length===50);return{page,errors,maps};}
async function click(page,s){const b=page.locator(s);await b.scrollIntoViewIfNeeded();if(await page.evaluate(()=>matchMedia('(pointer:coarse)').matches))await b.tap();else await b.click();}
async function project(page){return page.evaluate(()=>structuredClone(FloorPlanApp.project));}
async function open(page,kind='floor'){await page.evaluate(kind=>{select({kind:'room',id:FloorPlanApp.project.rooms[0].id});FloorPlanSurfaceUI.open({kind,id:FloorPlanApp.project.rooms[0].id});},kind);await page.locator('#surfaceDialog').waitFor({state:'visible'});}
async function ready(page){try{await page.waitForFunction(()=>View3D.surfaceMetrics.length>0&&View3D.surfaceMetrics.every(m=>m.state==='ready'),null,{timeout:15000});}catch(e){throw Error(e.message+' '+JSON.stringify(await page.evaluate(()=>View3D.surfaceMetrics)));}}
for(const vp of [{width:1440,height:900},{width:390,height:844},{width:844,height:390}])test(`surface library touch / keyboard / persistence / software 3D ${vp.width}x${vp.height}`,{timeout:120000},async t=>{
 const {page,errors,maps}=await setup(t,vp),original=await project(page);assert.equal(maps.length,0,'opening app must not load the texture inventory');await open(page);assert.equal(await page.locator('#surfaceFamily option').count(),6);
 for(const family of ['wood','ceramic','stone','mineral','wall']){await page.selectOption('#surfaceFamily',family);assert.equal(await page.locator('[data-surface]').count(),family==='wall'?0:10);}await page.selectOption('#surfaceFamily','wood');await page.fill('#surfaceSearch','espiga');assert.equal(await page.locator('[data-surface]').count(),1);await click(page,'[data-surface]');const before=await project(page);assert.deepEqual(before,original);const contrast=await page.locator('#surfaceApply').evaluate(b=>{const c=getComputedStyle(b),lum=s=>{const rgb=s.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;},a=lum(c.color),z=lum(c.backgroundColor);return(Math.max(a,z)+.05)/(Math.min(a,z)+.05);});assert.ok(contrast>=4.5,'Apply label must remain readable');await page.screenshot({path:`${QA}/${vp.width}x${vp.height}-library.png`});await click(page,'#surfaceCancel');assert.deepEqual(await project(page),original);
 await open(page);await page.fill('#surfaceSearch','espiga');await click(page,'[data-surface]');await page.fill('#surfaceRepeatX','2000');await page.fill('#surfaceRepeatY','3000');await click(page,'#surfaceApply');const floor=await project(page),rid=floor.rooms[0].id,mid=floor.rooms[0].floorMaterialId;assert.equal(floor.materials.find(m=>m.id===mid).appearance.preset,'surface-herringbone-parquet');assert.deepEqual(floor.openings,original.openings);assert.deepEqual(floor.objects,original.objects);
 assert.equal(await page.locator(`#defs #m-${mid} image`).getAttribute('href'),'assets/materials/herringbone-parquet-sample.webp');await click(page,'#undo');assert.deepEqual(await project(page),original);await click(page,'#redo');assert.deepEqual(await project(page),floor);
 await open(page,'wall');await page.selectOption('#surfaceFamily','wall');assert.equal(await page.locator('[data-surface]').count(),10);assert.match(await page.locator('#surfaceDialog').textContent(),/ambas caras/);await click(page,'[data-surface="surface-white-plaster-02"]');await click(page,'#surfaceApply');const painted=await project(page);assert.ok(painted.walls[0].surfaceMaterialId);assert.deepEqual(painted.openings,original.openings);
 await click(page,'[data-view="3d"]');await page.waitForFunction(()=>!document.body.classList.contains('busy'));await ready(page);const metrics=await page.evaluate(()=>({maps:View3D.surfaceMetrics,memory:View3D.rendererMemory,canvas:document.querySelector('#view3d canvas').clientHeight,stage:document.querySelector('#stage').clientHeight,walls:View3D.wallMeshes}));assert.ok(metrics.canvas>=metrics.stage*.6);assert.deepEqual(metrics.maps.find(m=>m.id==='surface-herringbone-parquet').map.repeat,[.5,1/3]);assert.ok(metrics.maps.every(m=>m.map.colorSpace==='srgb'));await page.screenshot({path:`${QA}/${vp.width}x${vp.height}-3d.png`});
 await click(page,'[data-view="2d"]');await page.waitForFunction(()=>!document.body.classList.contains('busy'));await page.reload();assert.deepEqual(await project(page),painted);await page.locator('details.menu summary').click();const pending=page.waitForEvent('download');await page.locator('#exportJson').click();const dl=await pending,stream=await dl.createReadStream(),chunks=[];for await(const c of stream)chunks.push(c);const exported=JSON.parse(Buffer.concat(chunks).toString());assert.deepEqual(exported,painted);await page.locator('#fileIn').setInputFiles({name:'surface-home.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await page.waitForFunction(()=>/importad|imported|导入/i.test(document.querySelector('#toast').textContent));assert.deepEqual(await project(page),painted);
 await open(page);await page.keyboard.press('Escape');assert.equal(await page.locator('#surfaceDialog').isVisible(),false);await page.screenshot({path:`${QA}/${vp.width}x${vp.height}-2d.png`});assert.deepEqual(errors,[]);await fs.writeFile(`${QA}/${vp.width}x${vp.height}-metrics.json`,JSON.stringify({viewport:vp,input:vp.width<1000?'touch taps':'mouse and keyboard',rendering:'Chromium SwiftShader software',metrics,mapRequests:maps.length,pageErrors:errors},null,2)+'\n');
});
test('every individual asset decodes, renders and disposes; mixed scene records transfer, memory and frame time',{timeout:300000},async t=>{const {page,errors}=await setup(t);await page.evaluate(()=>{const p=FloorPlanRoomLayout.create(FloorPlanRoomLayout.blank('QA acabados'),{name:'Estancia QA',width:4000,depth:3000,x:0,y:0}).project;FloorPlanApp.importProject(p);});await click(page,'[data-view="3d"]');await page.waitForFunction(()=>!document.body.classList.contains('busy'));const results=[];
 for(const entry of entries){await page.evaluate(e=>{const p=FloorPlanApp.project,kind=e.applications.includes('floor')?'floor':'wall',id=(kind==='floor'?p.rooms:p.walls)[0].id;FloorPlanApp.importProject(FloorPlanSurfaces.apply(p,e,{kind,id}));View3D.refreshSurfaces();},entry);await ready(page);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const result=await page.evaluate(id=>View3D.surfaceMetrics.find(m=>m.id===id),entry.id);assert.equal(result.state,'ready');assert.ok(result.gpuBytes>0);results.push({...result,source:entry.source,format:entry.maps.baseColor.format,resolution:[entry.maps.baseColor.width,entry.maps.baseColor.height],test:'actual local Rubik 3D rendering / SwiftShader'});}
 await page.evaluate(()=>{let p=FloorPlanCore.initial();for(const [i,f]of ['wood','ceramic','stone','mineral'].entries())p=FloorPlanSurfaces.apply(p,FloorPlanSurfaces.entries.find(e=>e.family===f),{kind:'floor',id:p.rooms[i].id});p=FloorPlanSurfaces.apply(p,FloorPlanSurfaces.entries.find(e=>e.family==='wall'),{kind:'wall',id:p.walls[0].id});FloorPlanApp.importProject(p);View3D.refreshSurfaces();});await ready(page);const mixed=await page.evaluate(async()=>{const intervals=[];let prev=performance.now();for(let i=0;i<30;i++){await new Promise(requestAnimationFrame);const n=performance.now();intervals.push(n-prev);prev=n;}const r=View3D.surfaceMetrics;return{active:r,estimatedGpuBytes:r.reduce((n,m)=>n+m.gpuBytes,0),downloadedMapBytes:r.reduce((n,m)=>n+m.bytes,0),memory:View3D.rendererMemory,disposals:View3D.surfaceDisposals.length,frameIntervalMs:{median:intervals.sort((a,b)=>a-b)[15],max:Math.max(...intervals)},environment:'Desktop Chromium headless / SwiftShader; not mobile hardware'};});assert.equal(mixed.active.length,5);assert.ok(mixed.disposals>0);await page.screenshot({path:`${QA}/desktop-mixed-3d.png`});await fs.writeFile(`${QA}/per-material-render-results.json`,JSON.stringify(results,null,2)+'\n');await page.evaluate(()=>{FloorPlanApp.importProject(FloorPlanCore.initial());View3D.refreshSurfaces();});mixed.baseline=await page.evaluate(async()=>{const samples=[];let prev=performance.now();for(let i=0;i<30;i++){await new Promise(requestAnimationFrame);const now=performance.now();samples.push(now-prev);prev=now;}return{fixture:'same reference home / original procedural floors / no surface assignments',memory:View3D.rendererMemory,activeSurfaceCount:View3D.surfaceMetrics.length,medianFrameIntervalMs:samples.sort((a,b)=>a-b)[15],maxFrameIntervalMs:Math.max(...samples)};});assert.equal(mixed.baseline.activeSurfaceCount,0);await fs.writeFile(`${QA}/mixed-scene-metrics.json`,JSON.stringify(mixed,null,2)+'\n');assert.deepEqual(errors,[]);
});
test('HTTP, hash, decode, unknown preset and catalogue failures remain visible with safe fallback',{timeout:120000},async t=>{const {page}=await setup(t);const e=entries[0];await page.route('**/'+e.maps.baseColor.path,route=>route.fulfill({status:404,body:'missing'}));await page.evaluate(e=>{FloorPlanApp.importProject(FloorPlanSurfaces.apply(FloorPlanApp.project,e,{kind:'floor',id:FloorPlanApp.project.rooms[0].id}));},e);await click(page,'[data-view="3d"]');await page.waitForFunction(()=>View3D.surfaceMetrics.some(m=>m.state==='fallback'));assert.match(await page.locator('#surfaceQAStatus').textContent(),/HTTP 404/);assert.ok(await page.evaluate(()=>View3D.rendererMemory.geometries>0));await page.screenshot({path:`QA_PLACEHOLDER/fallback-404.png`.replace('QA_PLACEHOLDER',QA)});
 await page.unroute('**/'+e.maps.baseColor.path);await page.route('**/'+e.maps.baseColor.path,async route=>{const b=Buffer.from(await fs.readFile(e.maps.baseColor.path));b[20]^=1;await route.fulfill({status:200,contentType:'image/webp',body:b});});await page.evaluate(()=>View3D.refreshSurfaces());await page.evaluate(()=>{const p=structuredClone(FloorPlanApp.project);p.materials.find(m=>m.id===p.rooms[0].floorMaterialId).appearance.repeatMm={x:1100,y:1000};FloorPlanApp.importProject(p);});await page.waitForFunction(()=>View3D.surfaceMetrics.some(m=>/SHA-256/.test(m.error||'')));assert.match(await page.locator('#surfaceQAStatus').textContent(),/SHA-256/);
 await page.unroute('**/'+e.maps.baseColor.path);const junk=Buffer.from('not-an-image'),digest=require('node:crypto').createHash('sha256').update(junk).digest('hex');await page.route('**/'+e.maps.baseColor.path,r=>r.fulfill({status:200,contentType:'image/webp',body:junk}));await page.evaluate(({id,bytes,digest})=>{const entry=FloorPlanSurfaces.get(id);entry.maps.baseColor.bytes=bytes;entry.maps.baseColor.sha256=digest;const p=structuredClone(FloorPlanApp.project);p.materials.find(m=>m.id===p.rooms[0].floorMaterialId).appearance.repeatMm={x:1200,y:1000};FloorPlanApp.importProject(p);},{id:e.id,bytes:junk.length,digest});await page.waitForFunction(()=>View3D.surfaceMetrics.some(m=>m.state==='fallback'&&!/SHA-256|HTTP/.test(m.error||'')));assert.match(await page.locator('#surfaceQAStatus').textContent(),/respaldo/);
 await page.evaluate(()=>{const p=structuredClone(FloorPlanApp.project);p.materials.find(m=>m.id===p.rooms[0].floorMaterialId).appearance.preset='surface-unknown';FloorPlanApp.importProject(p);});assert.match(await page.locator('#surfaceQAStatus').textContent(),/desconocido/);await click(page,'[data-view="2d"]');await page.waitForFunction(()=>!document.body.classList.contains('busy'));assert.ok(await page.locator('#gRooms polygon').count());await page.route('**/assets/materials/catalog.json',r=>r.fulfill({status:503,body:'unavailable'}));await page.reload();await page.waitForFunction(()=>FloorPlanSurfaces.status.has('catalog'));assert.match(await page.locator('#surfaceQAStatus').textContent(),/HTTP 503/);assert.ok(await page.locator('#gRooms polygon').count());
});

test('cancel, invalid scale and failed persistence preserve the project and history',{timeout:60000},async t=>{const {page}=await setup(t),original=await project(page);await open(page);await click(page,'[data-surface] >> nth=0');await page.fill('#surfaceRepeatX','0');await click(page,'#surfaceApply');assert.match(await page.locator('#surfaceError').textContent(),/100 y 10000/);assert.deepEqual(await project(page),original);await page.fill('#surfaceRepeatX','1000');await page.evaluate(()=>{Storage.prototype.setItem=function(){throw Error('QA storage unavailable');};});await click(page,'#surfaceApply');assert.match(await page.locator('#surfaceError').textContent(),/QA storage unavailable/);assert.deepEqual(await project(page),original);await click(page,'#surfaceCancel');assert.equal(await page.locator('#undo').isDisabled(),true);});

test('comparison is real and new surfaces never acquire a zero price in English or Chinese',{timeout:60000},async t=>{const {page,errors}=await setup(t),original=await project(page);await open(page);await click(page,'[data-surface="surface-wood-floor"]');await click(page,'[data-surface="surface-herringbone-parquet"]');assert.equal(await page.locator('.surface-comparison img').count(),2);assert.match(await page.locator('.surface-comparison').textContent(),/Tablón de madera natural/);assert.match(await page.locator('.surface-comparison').textContent(),/Parqué en espiga/);await click(page,'#surfaceCancel');assert.deepEqual(await project(page),original);await page.evaluate(()=>{const p=FloorPlanApp.project;FloorPlanApp.importProject(FloorPlanSurfaces.apply(p,FloorPlanSurfaces.get('surface-herringbone-parquet'),{kind:'floor',id:p.rooms[0].id}));});for(const language of ['en','zh']){await page.evaluate(language=>{LANG=language;select({kind:'room',id:FloorPlanApp.project.rooms[0].id});},language);assert.equal(await page.locator('#panel .total').count(),0);await page.evaluate(()=>select(null));assert.equal(await page.locator('#panel').textContent().then(s=>s.includes('¥')),false);}assert.deepEqual(errors,[]);});
