const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const C=require('../js/project-core.js'),T=require('../js/tracing-core.js'),P=require('../js/project-package.js'),Library=require('../js/project-library.js');
const bytes=new Uint8Array(fs.readFileSync(__dirname+'/fixtures/manual-plan.png'));
function seed(){const p=T.blank();p.sourceImages=[{id:'img_synthetic',mediaType:'image/png',widthPx:480,heightPx:320,storage:{kind:'local-browser',ref:'img_bytes'},placement:{originMm:{x:100,y:200},rotationDeg:0,mmPerPixel:10},visible:true,opacity:.55}];return p;}
function calibrated(){const p=seed();T.calibrate(p,'img_synthetic',{x:50,y:50},{x:450,y:50},4000);T.verify(p,{x:50,y:250},{x:450,y:250},4000);T.confirm(p);return p;}
test('image signatures/types/dimensions and strict application limits',()=>{assert.equal(T.imageInfo(bytes,'image/png').widthPx,480);assert.throws(()=>T.imageInfo(bytes,'image/jpeg'));assert.throws(()=>T.imageInfo(new Uint8Array(100)));assert.throws(()=>T.imageInfo(new Uint8Array(T.LIMITS.bytes+1)));const large=bytes.slice();new DataView(large.buffer).setUint32(16,8001);assert.throws(()=>T.imageInfo(large),/8000/);});
test('image/world transforms retain original pixels with rotation and translation',()=>{for(const rotation of [-180,-90,0,45,90,180]){const image=seed().sourceImages[0];image.placement.rotationDeg=rotation;const pt={x:123.4,y:234.5},world=T.imageToWorld(image,pt),back=T.worldToImage(image,world);assert.ok(Math.hypot(back.x-pt.x,back.y-pt.y)<1e-9);}});
test('calibration, independent verification, confirmation and recalibration are coherent',()=>{const p=calibrated();assert.equal(p.scale.confidence,'real');assert.equal(p.scale.verification.errorPercent,0);C.validate(p);assert.throws(()=>T.verify(p,{x:50,y:50},{x:450,y:50},4000),/independiente/);T.verify(p,{x:50,y:250},{x:450,y:250},5000);assert.equal(p.scale.verification.status,'discrepant');assert.throws(()=>T.confirm(p));assert.equal(p.scale.confidence,'estimated');T.calibrate(p,'img_synthetic',{x:50,y:50},{x:450,y:50},4000);assert.equal(p.scale.verification,undefined);assert.equal(p.scale.calibration.confirmedByUser,false);});
test('schema and semantic verification reject forged points, measurements/status and confirmation',()=>{for(const fn of [p=>p.scale.verification.measuredLengthMm++,p=>p.scale.verification.errorPercent=20,p=>p.scale.verification.status='discrepant',p=>p.scale.calibration.confirmedByUser=false,p=>p.scale.verification.sourceImageId='img_missing',p=>p.scale.verification.pointB.x=5000]){const p=calibrated();fn(p);assert.throws(()=>C.validate(p));}assert.throws(()=>T.calibrate(seed(),'img_synthetic',{x:-1,y:0},{x:50,y:0},1000));assert.throws(()=>T.calibrate(seed(),'img_synthetic',{x:1,y:1},{x:1,y:1},1000));});
test('stable manual walls/openings/rooms, snapping, deletion and invalid polygon rejection',()=>{const p=seed(),w=T.wall(p,{x:0,y:0},{x:4000,y:0});T.opening(p,w.id,{x:1000,y:0},'door');T.opening(p,w.id,{x:3000,y:0},'window');const room=T.room(p,[{x:0,y:100},{x:4000,y:100},{x:4000,y:3000},{x:0,y:3000}]);assert.ok(w.id.startsWith('wal_'));assert.equal(p.openings[0].wallId,w.id);assert.deepEqual(T.snap({x:1,y:2},null,p.walls,true,20),{x:0,y:0});assert.deepEqual(T.snap({x:41,y:32},null,p.walls,false,20),{x:41,y:32});const q=T.snap({x:1000,y:50},{x:0,y:0},[],true,1);assert.equal(q.y,0);assert.throws(()=>T.room(C.clone(p),[{x:0,y:0},{x:100,y:100},{x:0,y:100},{x:100,y:0}]));T.remove(p,'wall',w.id);assert.equal(p.openings.length,0);T.remove(p,'room',room.id);C.validate(p);});
test('W1-W4 detect actual review, contour, furniture and scale without blocking',()=>{const p=seed();const corners=[{x:0,y:0},{x:4000,y:0},{x:4000,y:3000},{x:0,y:3000}];for(let i=0;i<4;i++)T.wall(p,corners[i],corners[(i+1)%4]);const r=T.room(p,corners);p.objects=[{id:'obj_generic',name:'Mueble',type:'bed',position:{x:2000,y:1500},size:{widthMm:1000,depthMm:1000},rotationDeg:0,roomId:r.id}];let out=T.warnings(p);assert.ok(out.some(w=>w.code==='W1'));assert.ok(out.some(w=>w.code==='W4'));assert.ok(!out.some(w=>w.code==='W2'||w.code==='W3'));p.objects[0].position.x=50;assert.ok(T.warnings(p).some(w=>w.code==='W3'));p.walls.pop();assert.ok(T.warnings(p).some(w=>w.code==='W2'));C.validate(p);});
test('W2 exactly covers segmented contours including tolerance around wall ends',()=>{const p=seed();p.walls=[];T.wall(p,{x:0,y:0},{x:1900,y:0});T.wall(p,{x:2100,y:0},{x:4000,y:0});T.wall(p,{x:4000,y:0},{x:4000,y:3000});T.wall(p,{x:4000,y:3000},{x:0,y:3000});T.wall(p,{x:0,y:3000},{x:0,y:0});T.room(p,[{x:0,y:0},{x:4000,y:0},{x:4000,y:3000},{x:0,y:3000}]);assert.ok(!T.warnings(p).some(w=>w.code==='W2'));p.walls[0].end.x=1000;assert.ok(T.warnings(p).some(w=>w.code==='W2'));});
test('W3 ignores the solid removed by a real opening',()=>{const p=seed();const w=T.wall(p,{x:0,y:0},{x:4000,y:0});T.opening(p,w.id,{x:2000,y:0},'door',1600);p.objects=[{id:'obj_box',name:'Caja',type:'box',position:{x:2000,y:0},size:{widthMm:500,depthMm:500},rotationDeg:0}];assert.ok(!T.warnings(p).some(w=>w.code==='W3'));});
test('ZIP round-trip keeps full geometry, original image bytes and private filenames out',async()=>{const p=calibrated();p.sourceImages[0].originalFileName='direccion-personal.png';const blob=await P.encode(p,async()=>new Blob([bytes]));const entries=await P.unzip(await blob.arrayBuffer()),result=await P.validateEntries(entries);assert.equal(result.project.sourceImages[0].originalFileName,undefined);assert.deepEqual(result.images[0].bytes,bytes);assert.deepEqual(result.project.scale,p.scale);assert.equal(result.project.sourceImages[0].storage.kind,'sidecar-file');});
test('ZIP rejects corruption, CRC, duplicate names, escape paths, broken refs and limits',async()=>{const p=seed(),blob=await P.encode(p,async()=>new Blob([bytes])),valid=new Uint8Array(await blob.arrayBuffer());const corrupted=valid.slice();corrupted[40]^=1;await assert.rejects(()=>P.unzip(corrupted));await assert.rejects(()=>P.unzip(new Uint8Array(10)));assert.throws(()=>P.zip(new Map([['../escape',new Uint8Array(1)]])));const entries=await P.unzip(valid);const missing=new Map(entries);missing.delete('images/img_synthetic.png');await assert.rejects(()=>P.validateEntries(missing));const extra=new Map(entries);extra.set('images/img_extra.png',bytes);await assert.rejects(()=>P.validateEntries(extra));const inflated=valid.slice(),view=new DataView(inflated.buffer),end=inflated.length-22,offset=view.getUint32(end+16,true);view.setUint32(offset+24,T.LIMITS.bytes+1,true);await assert.rejects(()=>P.unzip(inflated));});
test('ZIP DEFLATE input is bounded and valid (independent compressed fixture)',async()=>{const zlib=require('node:zlib'),data=new TextEncoder().encode('{}'),encoded=zlib.deflateRawSync(data),stored=new Uint8Array(await P.zip(new Map([['project.json',data]])).arrayBuffer());const head=stored.slice(0,42),central=stored.slice(44,102),end=stored.slice(102),h=new DataView(head.buffer),c=new DataView(central.buffer),e=new DataView(end.buffer);h.setUint16(8,8,true);h.setUint32(18,encoded.length,true);c.setUint16(10,8,true);c.setUint32(20,encoded.length,true);e.setUint32(16,42+encoded.length,true);const zip=new Blob([head,encoded,central,end]);assert.deepEqual((await P.unzip(await zip.arrayBuffer())).get('project.json'),data);});
test('old V1 projects remain valid without new optional verification/opacity',()=>{const old=require('../docs/contracts/examples/floorplan-project-v1.example.json');C.validate(old);assert.deepEqual(C.prepare(old).project,old);});
test('new project collection writes are atomic on storage failure',()=>{const storage={getItem:()=>null,setItem:()=>{throw Error('quota');}},lib=Library.load(storage,C.initial()),before=lib.all();assert.throws(()=>lib.add(seed(),'Imported'),/quota/);assert.deepEqual(lib.all(),before);});

test('snap accepts DOMPoint-like inherited coordinates from the actual SVG conversion',()=>{const p=Object.create({x:40.2,y:30.7});assert.deepEqual(T.snap(p,null,[],true,20),{x:40,y:31});});
test('JPEG and EXIF rotations retain original bytes/pixels, neutralizing display copy only',()=>{const jpeg=new Uint8Array(fs.readFileSync(__dirname+'/fixtures/manual-plan-exif6.jpg')),info=T.imageInfo(jpeg,'image/jpeg');assert.equal(info.widthPx,480);assert.equal(info.heightPx,320);assert.equal(info.orientation,6);assert.equal(T.orientationAngle(info),90);const rendering=T.renderBytes(jpeg,info);assert.equal(T.imageInfo(rendering).orientation,1);assert.equal(T.imageInfo(jpeg).orientation,6);assert.notDeepEqual(rendering,jpeg);});
test('ZIP rejects duplicate entries and encrypted flags before touching a collection',async()=>{const raw=P.zip({size:2,*[Symbol.iterator](){yield ['project.json',new TextEncoder().encode('{}')];yield ['project.json',new TextEncoder().encode('{}')];}});await assert.rejects(()=>raw.arrayBuffer().then(b=>P.unzip(b)),/duplicado/);const b=new Uint8Array(await P.zip(new Map([['project.json',new TextEncoder().encode('{}')]])).arrayBuffer()),v=new DataView(b.buffer),at=v.getUint32(b.length-6,true);v.setUint16(at+8,1,true);await assert.rejects(()=>P.unzip(b),/cifrado/);});
test('ZIP inflation stops before accepting a payload larger than its declared bound',async()=>{const zlib=require('node:zlib'),data=new TextEncoder().encode('{}'),encoded=zlib.deflateRawSync(Buffer.alloc(100000,65)),stored=new Uint8Array(await P.zip(new Map([['project.json',data]])).arrayBuffer()),head=stored.slice(0,42),central=stored.slice(44,102),end=stored.slice(102);new DataView(head.buffer).setUint16(8,8,true);new DataView(head.buffer).setUint32(18,encoded.length,true);new DataView(central.buffer).setUint16(10,8,true);new DataView(central.buffer).setUint32(20,encoded.length,true);new DataView(end.buffer).setUint32(16,42+encoded.length,true);await assert.rejects(()=>new Blob([head,encoded,central,end]).arrayBuffer().then(b=>P.unzip(b)),/límite/);});
test('W3 catches a furniture footprint crossing a concave room even with all corners inside',()=>{const p=seed(),r=T.room(p,[{x:0,y:0},{x:4000,y:0},{x:4000,y:4000},{x:3000,y:4000},{x:3000,y:1000},{x:1000,y:1000},{x:1000,y:4000},{x:0,y:4000}]);p.objects=[{id:'obj_concave',name:'Caja',type:'box',position:{x:2000,y:2000},size:{widthMm:3000,depthMm:3000},rotationDeg:0,roomId:r.id}];assert.ok(T.warnings(p).some(w=>w.code==='W3'&&w.message.includes('estancia')));});

test('static WebP VP8 and VP8L preserve dimensions, calibration and original ZIP bytes',async()=>{
 for(const filename of ['manual-plan.webp','manual-plan-lossy.webp','manual-plan-alpha.webp']){
  const bytes=new Uint8Array(fs.readFileSync(__dirname+'/fixtures/'+filename)),info=T.imageInfo(bytes,'image/webp',filename);
  assert.equal(info.widthPx,480);assert.equal(info.heightPx,320);assert.equal(info.orientation,1);
  const p=seed();p.schemaVersion='1.2.0';p.sourceImages[0].mediaType='image/webp';
  T.calibrate(p,'img_synthetic',{x:50,y:50},{x:450,y:50},4000);T.verify(p,{x:50,y:250},{x:450,y:250},4000);T.confirm(p);
  assert.equal(p.schemaVersion,'1.2.0');
  const zip=await P.encode(p,async()=>new Blob([bytes])),entries=await P.unzip(await zip.arrayBuffer());
  assert.ok(entries.has('images/img_synthetic.webp'));const result=await P.validateEntries(entries);
  assert.deepEqual(result.images[0].bytes,bytes);assert.deepEqual(result.project.scale,p.scale);
  assert.equal(result.project.sourceImages[0].mediaType,'image/webp');
  const forged=new Map(entries),json=JSON.parse(new TextDecoder().decode(entries.get('project.json')));
  json.sourceImages[0].storage.ref='images/img_synthetic.png';forged.delete('images/img_synthetic.webp');forged.set('images/img_synthetic.png',bytes);forged.set('project.json',new TextEncoder().encode(JSON.stringify(json)));
  await assert.rejects(()=>P.validateEntries(forged),/extensión/);
 }
});
test('image ingestion validates empty MIME, extensions, WebP bounds and unsupported variants',()=>{
 const webp=new Uint8Array(fs.readFileSync(__dirname+'/fixtures/manual-plan.webp'));
 assert.equal(T.imageInfo(webp,'','plan.WEBP').mediaType,'image/webp');
 assert.throws(()=>T.imageInfo(webp,'image/png','plan.webp'),/tipo declarado/);
 assert.throws(()=>T.imageInfo(webp,'','plan.png'),/extensión/);
 assert.throws(()=>T.imageInfo(webp.slice(0,-1)),/truncado/);
 const extra=new Uint8Array(webp.length+1);extra.set(webp);assert.throws(()=>T.imageInfo(extra),/tamaño/);
 const oversized=webp.slice(),view=new DataView(oversized.buffer);const bits=view.getUint32(21,true);view.setUint32(21,(bits&~0x3fff)|8000,true);assert.throws(()=>T.imageInfo(oversized),/8000/);
 function prefix(kind,data){const chunk=Buffer.alloc(8+data.length+(data.length%2));chunk.write(kind);chunk.writeUInt32LE(data.length,4);Buffer.from(data).copy(chunk,8);const result=Buffer.concat([webp.subarray(0,12),chunk,webp.subarray(12)]);result.writeUInt32LE(result.length-8,4);return result;}
 assert.throws(()=>T.imageInfo(prefix('ANIM',new Uint8Array(6))),/animado/);
 assert.throws(()=>T.imageInfo(prefix('EXIF',new Uint8Array(6))),/EXIF/);
 const extended=Buffer.alloc(10);extended.writeUIntLE(479,4,3);extended.writeUIntLE(319,7,3);assert.equal(T.imageInfo(prefix('VP8X',extended)).widthPx,480);
 extended.writeUIntLE(8000,4,3);assert.throws(()=>T.imageInfo(prefix('VP8X',extended)),/8000/);
 assert.throws(()=>T.imageInfo(Buffer.from('%PDF-1.7'),'application/pdf','plan.pdf'),/PDF no admitido/);
 assert.throws(()=>T.imageInfo(Buffer.alloc(30),'','plan.heic'),/HEIC\/HEIF no admitido/);
});
