const {test}=require('node:test');
const assert=require('node:assert/strict');
const A=require('../js/wall-assist.js'),C=require('../js/project-core.js'),T=require('../js/tracing-core.js');
function raster(width=160,height=100,background=255){const data=new Uint8ClampedArray(width*height*4);for(let i=0;i<width*height;i++)data.set([background,background,background,255],i*4);return {width,height,data};}
function pixel(im,x,y,v=0){im.data.set([v,v,v,255],(y*im.width+x)*4);}
function horizontal(im,y,start=20,end=140){for(let x=start;x<=end;x++)for(let d=0;d<3;d++)pixel(im,x,y+d);}
function vertical(im,x){for(let y=10;y<90;y++)for(let d=0;d<3;d++)pixel(im,x+d,y);}
test('clear strokes yield centerline proposals and multiple independent candidates',()=>{const im=raster();horizontal(im,20);horizontal(im,60);vertical(im,150);const out=A.detect(im);assert.equal(out.length,3);assert.deepEqual(out[0].start,{x:20,y:21});assert.deepEqual(out[0].end,{x:140,y:21});assert.ok(out.some(c=>c.start.x===151&&c.end.x===151));assert.equal(new Set(out.map(c=>c.id)).size,3);});
test('short interruptions join but large gaps stay separate',()=>{const im=raster();horizontal(im,20);for(let x=70;x<=72;x++)for(let y=20;y<=22;y++)pixel(im,x,y,255);assert.equal(A.detect(im).length,1);for(let x=60;x<=85;x++)for(let y=20;y<=22;y++)pixel(im,x,y,255);assert.equal(A.detect(im).length,2);});
test('blank, uniform dark, low contrast and isolated noise abstain',()=>{for(const gray of [0,255])assert.deepEqual(A.detect(raster(160,100,gray)),[]);const low=raster(160,100,170);horizontal(low,20);for(let i=0;i<low.data.length;i+=4)if(low.data[i]===0)low.data.set([120,120,120,255],i);assert.deepEqual(A.detect(low),[]);const noise=raster();for(let y=1;y<100;y+=9)for(let x=1;x<160;x+=11)pixel(noise,x,y);assert.deepEqual(A.detect(noise),[]);});
test('transparent strokes do not fabricate lines and raster limits are enforced',()=>{const im=raster();horizontal(im,20);for(let i=0;i<im.data.length;i+=4)if(!im.data[i])im.data[i+3]=0;assert.deepEqual(A.detect(im),[]);assert.throws(()=>A.detect(raster(513,10)),/512/);assert.throws(()=>A.detect({width:1,height:1,data:new Uint8ClampedArray(0)}));});
test('sampling maps through original pixels, rotation and displacement with F1b transform',()=>{const image={widthPx:800,heightPx:400,placement:{originMm:{x:100,y:-200},rotationDeg:90,mmPerPixel:5}},candidate={id:'candidate_1',start:{x:10,y:20},end:{x:100,y:20}};const result=A.toWorld(candidate,image,400,200);assert.deepEqual(result,{id:candidate.id,start:{x:-100,y:-100},end:{x:-100,y:800}});});
test('explicit acceptance and correction reuse canonical IDs, source states and export validation',()=>{const p=T.blank(),before=C.clone(p),candidate={id:'candidate_1',start:{x:0,y:0},end:{x:1000,y:0}};const a=A.accept(p,candidate);assert.match(a.id,/^wal_/);assert.deepEqual(a.source,{method:'suggested',review:'confirmed'});const b=A.accept(p,candidate,{x:100,y:100},{x:1100,y:200});assert.notEqual(a.id,b.id);assert.deepEqual(b.start,{x:100,y:100});const saved=C.prepare(JSON.stringify(p)).project;assert.deepEqual(saved.walls,p.walls);assert.deepEqual(p.scale,before.scale);assert.deepEqual(p.openings,before.openings);assert.deepEqual(p.rooms,before.rooms);assert.ok(!JSON.stringify(saved).includes('candidate_'));assert.equal(C.geometry(saved).walls.length,2);});
test('invalid corrected geometry fails validation on a clone without changing live project',()=>{const p=T.blank(),before=JSON.stringify(p);assert.throws(()=>A.accept(C.clone(p),{start:{x:0,y:0},end:{x:0,y:0}}));assert.equal(JSON.stringify(p),before);});

test('synthetic detector timing is recorded without imposing product budgets',t=>{
 const im=raster();horizontal(im,20);horizontal(im,60);vertical(im,150);
 const samples=[];let result;for(let n=0;n<30;n++){const start=performance.now();result=A.detect(im);samples.push(performance.now()-start);}samples.sort((a,b)=>a-b);
 assert.equal(result.length,3);t.diagnostic(JSON.stringify({synthetic:true,method:'30 calls, clear 160x100 RGBA raster, detector only; no decode/UI',node:process.version,platform:process.platform,arch:process.arch,candidates:result.length,medianMs:samples[14],p90NearestRankMs:samples[26]}));
});
