'use strict';
// Pure, explicit offline exporter. Never imports storage, DOM, network or editor adapters.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const Core=require('../../js/project-core.js'),Catalog=require('../../js/asset-catalog.js'),Generic=require('../../js/generic-catalog.js'),GLB=require('./glb.cjs'),Profiles=require('./profiles.json');
const VERSION='1.0.0',repo=path.resolve(__dirname,'../..');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const canonical=x=>JSON.stringify(sort(x));
function sort(x){if(Array.isArray(x))return x.map(sort);if(x&&typeof x==='object')return Object.fromEntries(Object.keys(x).sort().map(k=>[k,sort(x[k])]));return x;}
function safeRead(root,relative){if(typeof relative!=='string'||!/^assets\/[A-Za-z0-9/_.-]+$/.test(relative)||relative.split('/').includes('..'))throw Error('Unsafe local resource path');const base=fs.realpathSync(root),full=fs.realpathSync(path.resolve(base,relative));if(!full.startsWith(base+path.sep))throw Error('Resource escapes repository');return fs.readFileSync(full);}
function checked(root,url,hash,bytes){const b=safeRead(root,url);if(b.length!==bytes||sha(b)!==hash)throw Error('Resource integrity failed: '+url);return b;}
const quatY=a=>[0,Math.sin(a/2),0,Math.cos(a/2)];
function eulerXYZ(deg){const [x,y,z]=deg.map(v=>v*Math.PI/360),c=[Math.cos(x),Math.cos(y),Math.cos(z)],s=[Math.sin(x),Math.sin(y),Math.sin(z)];return [s[0]*c[1]*c[2]+c[0]*s[1]*s[2],c[0]*s[1]*c[2]-s[0]*c[1]*s[2],c[0]*c[1]*s[2]+s[0]*s[1]*c[2],c[0]*c[1]*c[2]-s[0]*s[1]*s[2]];}
function triangulate(poly){
 const cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x),area=poly.reduce((v,a,i)=>{const b=poly[(i+1)%poly.length];return v+a.x*b.y-b.x*a.y;},0),ids=poly.map((_,i)=>i);if(area<0)ids.reverse();const out=[];
 // Remove redundant collinear vertices locally, without touching the project.
 for(let i=ids.length-1;i>=0&&ids.length>3;i--)if(cross(poly[ids[(i+ids.length-1)%ids.length]],poly[ids[i]],poly[ids[(i+1)%ids.length]])===0)ids.splice(i,1);
 while(ids.length>3){let found=false;for(let i=0;i<ids.length;i++){const a=ids[(i+ids.length-1)%ids.length],b=ids[i],c=ids[(i+1)%ids.length];if(cross(poly[a],poly[b],poly[c])<=0)continue;if(ids.some(j=>j!==a&&j!==b&&j!==c&&cross(poly[a],poly[b],poly[j])>=0&&cross(poly[b],poly[c],poly[j])>=0&&cross(poly[c],poly[a],poly[j])>=0))continue;out.push([a,c,b]);ids.splice(i,1);found=true;break;}if(!found)throw Error('Room triangulation failed');}out.push([ids[0],ids[2],ids[1]]);return out;
}
function cube(w,h,d){const v=[[-w/2,0,-d/2],[w/2,0,-d/2],[w/2,h,-d/2],[-w/2,h,-d/2],[-w/2,0,d/2],[w/2,0,d/2],[w/2,h,d/2],[-w/2,h,d/2]],faces=[[0,3,2,1],[4,5,6,7],[0,4,7,3],[1,2,6,5],[0,1,5,4],[3,7,6,2]];return faces.flatMap(([a,b,c,d])=>[[v[a],v[b],v[c]],[v[a],v[c],v[d]]]);}
function exportProject(input,{root=repo,python,signal}={}){
 if(signal?.aborted)throw Error('Export cancelled');const p=Core.clone(input),warnings=Core.validate(p),source=Buffer.from(canonical(p)+'\n'),center=Core.geometry(p).center;
 if(source.length>Profiles.package.jsonBytes)throw Error('Project JSON outside package limit');
 const doc={asset:{version:'2.0',generator:'Rubik offline exporter '+VERSION},scene:0,scenes:[{name:p.id,nodes:[]}],nodes:[],meshes:[],materials:[],accessors:[],bufferViews:[],buffers:[{byteLength:0}],images:[],textures:[],samplers:[]},chunks=[],entities=[],losses=[],resources=[],files=new Map([['source-project.json',source]]);let size=0,totalTriangles=0;
 const point=(x,y,z=0)=>[(x-center.x)/1000,z/1000,(y-center.y)/1000];
 function checkCancel(){if(signal?.aborted)throw Error('Export cancelled');}
 function view(bytes,target){const pad=(4-size%4)%4;if(pad){chunks.push(Buffer.alloc(pad));size+=pad;}const i=doc.bufferViews.length;doc.bufferViews.push({buffer:0,byteOffset:size,byteLength:bytes.length,...(target?{target}:{})});chunks.push(bytes);size+=bytes.length;return i;}
 function accessor(values,width){const b=Buffer.alloc(values.length*4);values.forEach((n,i)=>b.writeFloatLE(n,i*4));const a={bufferView:view(b,34962),componentType:5126,count:values.length/width,type:{2:'VEC2',3:'VEC3'}[width]};if(width===3){a.min=[0,1,2].map(j=>values.filter((_,i)=>i%3===j).reduce((x,y)=>Math.min(x,y),Infinity));a.max=[0,1,2].map(j=>values.filter((_,i)=>i%3===j).reduce((x,y)=>Math.max(x,y),-Infinity));}doc.accessors.push(a);return doc.accessors.length-1;}
 function node(name,role,props={}){const index=doc.nodes.length;doc.nodes.push({name,extras:{rubik_id:name,rubik_role:role},...props});return index;}
 function mesh(triangles,material,repeat=[1,1],uvMode='floor'){
  totalTriangles+=triangles.length;const vertices=[],normals=[],uv=[];for(const t of triangles){const [a,b,c]=t,u=b.map((v,i)=>v-a[i]),v=c.map((v,i)=>v-a[i]),n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],length=Math.hypot(...n);if(length===0)throw Error('Degenerate triangle');for(const q of t){vertices.push(...q);normals.push(...n.map(v=>v/length));uv.push(q[0]/repeat[0],q[uvMode==='wall'?1:2]/repeat[1]);}}
  const prim={attributes:{POSITION:accessor(vertices,3),NORMAL:accessor(normals,3),TEXCOORD_0:accessor(uv,2)},mode:4,material};doc.meshes.push({primitives:[prim]});return doc.meshes.length-1;
 }
 const materialIndex=new Map(),candidatePath=path.join(root,'assets/interop/surface-candidates.json'),surfaces=[...JSON.parse(fs.readFileSync(path.join(root,'assets/materials/catalog.json'))).entries,...(fs.existsSync(candidatePath)?JSON.parse(fs.readFileSync(candidatePath)).entries:[])];
 function addMaterial(id,color,roughness=.8){const linear=x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4,i=doc.materials.length;doc.materials.push({name:id,extras:{rubik_id:id},doubleSided:true,pbrMetallicRoughness:{baseColorFactor:[1,3,5].map(s=>linear(parseInt(color.slice(s,s+2),16)/255)).concat(1),metallicFactor:0,roughnessFactor:roughness}});return i;}
 for(const m of [...p.materials].sort((a,b)=>a.id.localeCompare(b.id))){const entry=surfaces.find(s=>s.id===m.appearance.preset),i=addMaterial(m.id,m.appearance.color,entry?.roughness??.8);materialIndex.set(m.id,i);if(entry){try{
   if(entry.source.license!=='CC0-1.0'||!python)throw Error('Surface permission/decoder unavailable');if(entry.source.rights){const rights=entry.source.rights;if(!rights.redistribution||!rights.modification||!rights.commercial)throw Error('Surface rights incomplete');checked(root,rights.licensePath,rights.licenseSha256,fs.statSync(path.join(root,rights.licensePath)).size);}const map=entry.maps.baseColor,b=checked(root,map.path,map.sha256,map.bytes);if(map.width>256||map.height>256)throw Error('Surface profile resolution');const png=execFileSync(python,[path.join(__dirname,'convert-texture.py'),...(map.format==='image/png'?['png-candidate']:[])],{input:b,maxBuffer:1048576}),texture=doc.textures.length;
   doc.images.push({name:entry.id,mimeType:'image/png',bufferView:view(png)});doc.textures.push({source:doc.images.length-1,sampler:0});if(!doc.samplers.length)doc.samplers.push({wrapS:10497,wrapT:10497,magFilter:9729,minFilter:9987});doc.materials[i].pbrMetallicRoughness.baseColorTexture={index:texture};doc.materials[i].pbrMetallicRoughness.baseColorFactor=[1,1,1,1];
   resources.push({kind:'surface',id:entry.id,profile:entry.profile||Profiles.surface.id,input:{path:map.path,bytes:b.length,sha256:sha(b)},output:{embeddedImage:doc.images.length-1,bytes:png.length,sha256:sha(png),format:'image/png'},provenance:entry.source,channels:Profiles.surface.channels,repeatMm:m.appearance.repeatMm||entry.repeatMm});
  }catch(e){losses.push({id:m.id,kind:'surface',reason:e.message,fallback:'declared color, scalar roughness'});}}else if(m.appearance.preset)losses.push({id:m.id,kind:'surface',reason:'Procedural or unknown preset not baked',fallback:'declared color'});
 }
 const defaultWall=addMaterial('rubik-default-wall','#e4dfd5');
 const repeat=id=>{const m=p.materials.find(m=>m.id===id),e=surfaces.find(s=>s.id===m?.appearance.preset),r=m?.appearance.repeatMm||e?.repeatMm||{x:1000,y:1000};return [r.x/1000,r.y/1000];};
 function entity(id,role,n,source,extra={}){entities.push({id,role,node:n,source,...extra});doc.scenes[0].nodes.push(n);}
 for(const r of [...p.rooms].sort((a,b)=>a.id.localeCompare(b.id))){const verts=r.polygon.map(v=>point(v.x,v.y)),triangles=triangulate(r.polygon).map(t=>t.map(i=>verts[i])),n=node(r.id,'room',{mesh:mesh(triangles,materialIndex.get(r.floorMaterialId),repeat(r.floorMaterialId))});entity(r.id,'room',n,r,{representation:'interior floor polygon at elevation 0; no inferred ceiling'});}
 for(const w of [...p.walls].sort((a,b)=>a.id.localeCompare(b.id))){const n=node(w.id,'wall',{children:[]}),length=Math.hypot(w.end.x-w.start.x,w.end.y-w.start.y),angle=Math.atan2(w.end.y-w.start.y,w.end.x-w.start.x),openings=p.openings.filter(o=>o.wallId===w.id),xs=[...new Set([0,length,...openings.flatMap(o=>[o.offsetMm,o.offsetMm+o.widthMm])])].sort((a,b)=>a-b),zs=[...new Set([0,w.heightMm,...openings.flatMap(o=>[o.sillHeightMm,o.sillHeightMm+o.heightMm])])].sort((a,b)=>a-b);let count=0,solidVolumeM3=0;
  if(w.status!=='demolished')for(let i=0;i<xs.length-1;i++)for(let j=0;j<zs.length-1;j++){const x=(xs[i]+xs[i+1])/2,z=(zs[j]+zs[j+1])/2;if(openings.some(o=>x>o.offsetMm&&x<o.offsetMm+o.widthMm&&z>o.sillHeightMm&&z<o.sillHeightMm+o.heightMm))continue;const len=xs[i+1]-xs[i],height=zs[j+1]-zs[j],child=node(w.id+'__solid_'+count++,'wall-fragment',{mesh:mesh(cube(len/1000,height/1000,w.thicknessMm/1000),materialIndex.get(w.surfaceMaterialId)??defaultWall,repeat(w.surfaceMaterialId),'wall'),translation:point(w.start.x+Math.cos(angle)*x,w.start.y+Math.sin(angle)*x,zs[j]),rotation:quatY(-angle)});doc.nodes[child].extras={rubik_parent_id:w.id,rubik_role:'wall-fragment',wall_interval_mm:[xs[i],xs[i+1],zs[j],zs[j+1]]};doc.nodes[n].children.push(child);solidVolumeM3+=len*height*w.thicknessMm/1e9;}
  entity(w.id,'wall',n,w,{fragmentCount:count,solidVolumeM3,representation:w.status==='demolished'?'metadata-only demolished wall':'axis thickness split by union of opening rectangles'});
 }
 for(const o of [...p.openings].sort((a,b)=>a.id.localeCompare(b.id))){const w=p.walls.find(w=>w.id===o.wallId),angle=Math.atan2(w.end.y-w.start.y,w.end.x-w.start.x),s=o.offsetMm+o.widthMm/2,n=node(o.id,'opening',{translation:point(w.start.x+Math.cos(angle)*s,w.start.y+Math.sin(angle)*s,o.sillHeightMm),rotation:quatY(-angle)});entity(o.id,'opening',n,o,{dimensionsMeters:[o.widthMm/1000,w.thicknessMm/1000,o.heightMm/1000],representation:'actual architectural void + semantic empty; no invented leaf/frame/glass'});}
 const localBytes=fs.readFileSync(path.join(root,'assets/f3/catalog.manifest.json')),local=Catalog.adapt(JSON.parse(localBytes),{catalog:'rubik-sota-local',revision:sha(localBytes).slice(0,40)}).entries,external=JSON.parse(fs.readFileSync(path.join(root,'assets/f3/external.manifest.json'))),catalog=[...local,...Catalog.adapt(external.source,{catalog:'immersphere-asset-lab',revision:external.catalogRevision,evidence:external.evidence}).entries];
 function merge(b){const {doc:a,bin}=GLB.parse(b),keys=['bufferViews','accessors','images','samplers','textures','materials','meshes','nodes'],offset=Object.fromEntries(keys.map(k=>[k,doc[k].length])),binView=view(bin),binOffset=doc.bufferViews[binView].byteOffset;
  // view(bin) appended a buffer view: remapped source views start AFTER it.
  offset.bufferViews=doc.bufferViews.length;
  for(const v of a.bufferViews||[])doc.bufferViews.push({...v,buffer:0,byteOffset:binOffset+(v.byteOffset||0)});
  for(const v of a.accessors||[])doc.accessors.push({...v,bufferView:v.bufferView+offset.bufferViews});
  for(const v of a.images||[])doc.images.push({...v,bufferView:v.bufferView+offset.bufferViews});
  for(const v of a.samplers||[])doc.samplers.push(v);
  for(const v of a.textures||[])doc.textures.push({...v,source:v.source+offset.images,...(v.sampler!==undefined?{sampler:v.sampler+offset.samplers}:{})});
  for(const v of a.materials||[]){const m=Core.clone(v);for(const t of [m.pbrMetallicRoughness?.baseColorTexture,m.pbrMetallicRoughness?.metallicRoughnessTexture,m.normalTexture,m.occlusionTexture])if(t)t.index+=offset.textures;doc.materials.push(m);}
  for(const m of a.meshes||[])doc.meshes.push({...m,primitives:m.primitives.map(v=>({...v,attributes:Object.fromEntries(Object.entries(v.attributes).map(([k,i])=>[k,i+offset.accessors])),...(v.indices!==undefined?{indices:v.indices+offset.accessors}:{}),...(v.material!==undefined?{material:v.material+offset.materials}:{})}))});
  for(const v of a.nodes||[])doc.nodes.push({...v,...(v.mesh!==undefined?{mesh:v.mesh+offset.meshes}:{}),...(v.children?{children:v.children.map(i=>i+offset.nodes)}:{})});return a.scenes[a.scene??0].nodes.map(i=>i+offset.nodes);
 }
 for(const o of [...p.objects].sort((a,b)=>a.id.localeCompare(b.id))){checkCancel();const height=o.size.heightMm??Generic.heights[o.type]??800,n=node(o.id,'object',{translation:point(o.position.x,o.position.y,o.elevationMm||0),rotation:quatY(-o.rotationDeg*Math.PI/180),children:[]});let representation='generic dimensional box (not the detailed browser procedural furniture)',asset;
  if(o.assetRef)try{const entry=Catalog.resolve(catalog,o.assetRef);if(!entry)throw Error('Unknown, unauthorized or revision-mismatched assetRef');checked(root,entry.permissionUrl,entry.permissionSha256,fs.statSync(path.join(root,entry.permissionUrl)).size);const b=checked(root,entry.url,entry.sha256,entry.bytes),metrics=GLB.inspect(b),parsed=GLB.parse(b),normalization={scale:[entry.normalization.unitToMeter,entry.normalization.unitToMeter,entry.normalization.unitToMeter],rotation:eulerXYZ(entry.normalization.rotationDeg)},bounds=GLB.bounds(parsed.doc,normalization,parsed.bin),dims=bounds.max.map((v,i)=>v-bounds.min[i]);if(dims.some((v,i)=>!(v>0)||Math.abs(v*1000-[entry.dimensionsMm.width,entry.dimensionsMm.height,entry.dimensionsMm.depth][i])>20))throw Error('Asset dimensions exceed F3 20 mm tolerance');const wanted=[o.size.widthMm/1000,height/1000,o.size.depthMm/1000],support=node(o.id+'__model-support','asset-support',{scale:wanted.map((v,i)=>v/dims[i]),children:[]}),normalized=node(o.id+'__normalized-model','asset-normalization',{...normalization,translation:[-(bounds.min[0]+bounds.max[0])/2,-bounds.min[1],-(bounds.min[2]+bounds.max[2])/2],children:merge(b)});doc.nodes[support].children.push(normalized);doc.nodes[n].children.push(support);totalTriangles+=metrics.triangles;representation='actual authorized catalog mesh, normalized and fitted like F3';asset={reference:o.assetRef,profile:Profiles.models.id,inputSha256:sha(b),inputBytes:b.length,permissionSha256:entry.permissionSha256,attribution:entry.attribution,normalization:entry.normalization,declaredCatalogDimensionsMm:entry.dimensionsMm,measuredMeshDimensionsMm:dims.map(v=>v*1000),instanceDimensionsMm:[o.size.widthMm,height,o.size.depthMm],metrics};resources.push({kind:'model',id:o.id,...asset});
  }catch(e){losses.push({id:o.id,kind:'asset',reason:e.message,fallback:'generic dimensional box; assetRef retained in semantic manifest'});}
  if(!asset)doc.nodes[n].mesh=mesh(cube(o.size.widthMm/1000,height/1000,o.size.depthMm/1000),addMaterial(o.id+'__color',o.color||'#999999'));
  entity(o.id,'object',n,o,{representation,asset:asset||null,heightOrigin:o.size.heightMm===undefined?'generic type fallback, not persisted':'explicit project height',dimensionsMeters:[o.size.widthMm/1000,o.size.depthMm/1000,height/1000]});
 }
 for(const i of p.sourceImages||[])losses.push({id:i.id,kind:'source-image',reason:'Private source raster not copied; reference only in source-project.json'});
 for(const m of p.measurements||[])losses.push({id:m.id,kind:'measurement',reason:'Dimension annotation preserved in source-project.json, not modeled'});
 if(p.extensions)losses.push({id:p.id,kind:'extensions',reason:'Extension data preserved in source-project.json, not interpreted'});
 checkCancel();if(!entities.length)throw Error('No entities to export');if(totalTriangles>Profiles.package.triangles||doc.nodes.length>Profiles.package.nodes||doc.textures.length>Profiles.package.textures)throw Error('Scene outside offline package budget');doc.buffers[0].byteLength=size;const packedDoc=Core.clone(doc);for(const n of packedDoc.nodes)if(n.children?.length===0)delete n.children;for(const key of ['images','textures','samplers','accessors','bufferViews','meshes'])if(packedDoc[key].length===0)delete packedDoc[key];const scene=GLB.pack(packedDoc,Buffer.concat(chunks));files.set('scene.glb',scene);
 const sourceFiles=['scripts/interop/export.cjs','scripts/interop/glb.cjs','scripts/interop/profiles.json','scripts/interop/convert-texture.py','js/project-core.js','js/project-schema.js','js/asset-catalog.js','js/generic-catalog.js'];
 const semantic={format:'rubik-blender-semantic',version:VERSION,projectId:p.id,contractVersion:p.schemaVersion,projectSha256:sha(source),exporter:{version:VERSION,node:process.version,sourceSha256:sha(fs.readFileSync(__filename)),profilesSha256:sha(fs.readFileSync(path.join(__dirname,'profiles.json'))),sources:Object.fromEntries(sourceFiles.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))])),encoders:{surface:'Pillow 12.3.0 when PNG conversion succeeds',geometry:'Node Buffer float32 writer; no third-party decoder'}},coordinateMapping:{source:'plan-top-left / mm / x right / y down / clockwise degrees',centerMm:center,gltf:'meters / X=(x-cx)/1000,Y=elevation/1000,Z=(y-cy)/1000 / yaw Y=-rotationDeg',blender:'meters / X=gltf.X,Y=-gltf.Z,Z=gltf.Y / yaw Z=-rotationDeg',originPolicy:'Core.geometry envelope including source placements; recorded, never inferred again'},entities,resources,omittedOrSubstituted:losses,warnings,metrics:{nodes:doc.nodes.length,triangles:totalTriangles,images:doc.images.length,materials:doc.materials.length},options:{sourceImages:false,ceilings:false,openingDecoration:false,catalogMeshes:true,colorFallback:true}};
 files.set('semantic.json',Buffer.from(canonical(semantic)+'\n'));let total=0;for(const b of files.values())total+=b.length;if(total>Profiles.package.bytes)throw Error('Package exceeds 64 MiB');const hashes=Object.fromEntries([...files].map(([name,b])=>[name,{sha256:sha(b),bytes:b.length}]));files.set('package.json',Buffer.from(canonical({format:'rubik-blender-package',version:VERSION,semanticSha256:hashes['semantic.json'].sha256,files:hashes,manifestSelfHash:'Not recursive: use external package.json digest in run evidence'})+'\n'));return {files,semantic,doc};
}
function writePackage(result,destination){if(fs.existsSync(destination))throw Error('Destination exists; refusing overwrite');fs.mkdirSync(destination,{recursive:true});for(const [name,b]of result.files)fs.writeFileSync(path.join(destination,name),b,{flag:'wx'});}
if(require.main===module){try{const [source,dest,python]=process.argv.slice(2);if(!source||!dest)throw Error('Usage: node scripts/interop/export.cjs project.json NEW-output-folder [python-executable]');const p=JSON.parse(fs.readFileSync(source,'utf8')),result=exportProject(p,{python});writePackage(result,dest);console.log(JSON.stringify({output:dest,entities:result.semantic.entities.length,...result.semantic.metrics,substitutions:result.semantic.omittedOrSubstituted}));}catch(e){console.error(e.message);process.exitCode=1;}}
module.exports={exportProject,writePackage,canonical,sha,triangulate,safeRead};
