'use strict';
const P=require('./profiles.json');
function parse(bytes){
 if(!Buffer.isBuffer(bytes)||bytes.length<28||bytes.toString('ascii',0,4)!=='glTF'||bytes.readUInt32LE(4)!==2||bytes.readUInt32LE(8)!==bytes.length)throw Error('Invalid GLB header/length');
 let at=12,doc,bin;while(at<bytes.length){if(at+8>bytes.length)throw Error('Truncated GLB');const n=bytes.readUInt32LE(at),t=bytes.readUInt32LE(at+4);if(n%4||at+8+n>bytes.length)throw Error('Invalid GLB chunk');const b=bytes.subarray(at+8,at+8+n);if(t===0x4e4f534a&&!doc&&at===12)doc=JSON.parse(b.toString('utf8'));else if(t===0x004e4942&&doc&&!bin)bin=b;else throw Error('Unsupported GLB chunks');at+=8+n;}
 if(doc?.asset?.version!=='2.0'||!bin||doc.buffers?.length!==1||'uri' in doc.buffers[0]||!Number.isSafeInteger(doc.buffers[0].byteLength)||doc.buffers[0].byteLength<1||doc.buffers[0].byteLength>bin.length||bin.length-doc.buffers[0].byteLength>3)throw Error('Invalid GLB buffer');return {doc,bin};
}
function pack(doc,bin){const pad=(b,v)=>Buffer.concat([b,Buffer.alloc((4-b.length%4)%4,v)]),j=pad(Buffer.from(JSON.stringify(doc)),32),b=pad(bin,0),out=Buffer.alloc(28+j.length+b.length);out.write('glTF');out.writeUInt32LE(2,4);out.writeUInt32LE(out.length,8);out.writeUInt32LE(j.length,12);out.writeUInt32LE(0x4e4f534a,16);j.copy(out,20);out.writeUInt32LE(b.length,20+j.length);out.writeUInt32LE(0x004e4942,24+j.length);b.copy(out,28+j.length);return out;}
function jpegSize(b){if(b[0]!==255||b[1]!==216||b.at(-2)!==255||b.at(-1)!==217)throw Error('Invalid JPEG');let p=2;while(p<b.length){if(b[p++]!==255)throw Error('Invalid JPEG marker');while(b[p]===255)p++;const m=b[p++],n=b.readUInt16BE(p);if(n<2||p+n>b.length)throw Error('Invalid JPEG segment');if([192,193,194].includes(m))return [b.readUInt16BE(p+5),b.readUInt16BE(p+3)];p+=n;}throw Error('JPEG size missing');}
function inspect(bytes,{allowPng=false}={}){
 const l=P.models.limits;if(bytes.length>l.bytes)throw Error('Profile: model over 8 MiB');const {doc:d,bin}=parse(bytes);
 function walk(v){if(!v||typeof v!=='object')return;if(v.extensions&&Object.keys(v.extensions).length)throw Error('Profile: extensions rejected');for(const x of Object.values(v))walk(x);}walk(d);
 if(d.extensionsUsed?.length||d.extensionsRequired?.length||d.animations?.length||d.skins?.length)throw Error('Profile: extensions/animation/skin rejected');
 if(!d.meshes?.length||d.images?.length>l.images||d.textures?.length>l.textures||d.materials?.length>l.materials)throw Error('Profile: scene/image/texture/material count');
 for(const v of d.bufferViews||[])if(v.buffer!==0||!Number.isSafeInteger(v.byteLength)||v.byteLength<1||!Number.isSafeInteger(v.byteOffset??0)||(v.byteOffset??0)<0||(v.byteOffset||0)+v.byteLength>d.buffers[0].byteLength)throw Error('Profile: invalid buffer view');
 for(const a of d.accessors||[])if(a.sparse||!Number.isSafeInteger(a.count)||a.count<1||a.count>l.accessorCount||!d.bufferViews[a.bufferView])throw Error('Profile: accessor outside limit');
 let triangles=0,vertices=0;const views=new Set();for(const m of d.meshes)for(const p of m.primitives||[]){if((p.mode??4)!==4||p.targets?.length||!d.accessors[p.attributes?.POSITION])throw Error('Profile: non-triangle/morph/position');const a=d.accessors[p.attributes.POSITION],n=p.indices===undefined?a.count:d.accessors[p.indices]?.count;if(!Number.isSafeInteger(n)||n%3)throw Error('Profile: invalid triangle count');triangles+=n/3;vertices+=a.count;for(const i of [...Object.values(p.attributes),...(p.indices===undefined?[]:[p.indices])]){if(!d.accessors[i])throw Error('Profile: invalid accessor index');views.add(d.accessors[i].bufferView);}}
 const geometryBytes=[...views].reduce((n,i)=>n+d.bufferViews[i].byteLength,0);if(triangles>l.triangles||vertices>l.vertices||geometryBytes>l.geometryBytes)throw Error('Profile: geometry budget');
 let decodedImageBytes=0;const images=(d.images||[]).map(i=>{if('uri' in i||!['image/jpeg',...(allowPng?['image/png']:[])].includes(i.mimeType)||!d.bufferViews[i.bufferView])throw Error('Profile: unsupported embedded image');const v=d.bufferViews[i.bufferView];if(v.byteLength>l.imageBytes)throw Error('Profile: image bytes');const b=bin.subarray(v.byteOffset||0,(v.byteOffset||0)+v.byteLength);let width,height;if(i.mimeType==='image/jpeg')[width,height]=jpegSize(b);else {if(b.length<33||b.subarray(0,8).toString('hex')!=='89504e470d0a1a0a'||b.toString('ascii',12,16)!=='IHDR'||b[24]!==8||![0,2,4,6].includes(b[25]))throw Error('Profile: unsupported PNG header');width=b.readUInt32BE(16);height=b.readUInt32BE(20);}if(width<1||height<1||width>l.imageSide||height>l.imageSide)throw Error('Profile: image resolution');decodedImageBytes+=width*height*4;return {mime:i.mimeType,width,height,bytes:v.byteLength};});
 if(decodedImageBytes>l.decodedImageBytes)throw Error('Profile: decoded image budget');
 for(const t of d.textures||[])if(!Number.isSafeInteger(t.source)||!d.images?.[t.source])throw Error('Profile: texture reference');
 for(const m of d.materials||[]){if(m.emissiveTexture)throw Error('Profile: emissive texture unsupported');for(const t of [m.pbrMetallicRoughness?.baseColorTexture,m.pbrMetallicRoughness?.metallicRoughnessTexture,m.normalTexture,m.occlusionTexture])if(t&&(!d.textures?.[t.index]||(t.texCoord??0)!==0))throw Error('Profile: material map reference');}
 return {triangles,vertices,geometryBytes,images,materials:d.materials?.length||0,bytes:bytes.length};
}
const rotate=(v,q)=>{const [x,y,z,w]=q,[a,b,c]=v,tx=2*(y*c-z*b),ty=2*(z*a-x*c),tz=2*(x*b-y*a);return [a+w*tx+y*tz-z*ty,b+w*ty+z*tx-x*tz,c+w*tz+x*ty-y*tx];};
function transform(v,n){if(n.matrix){const m=n.matrix;return [0,1,2].map(i=>m[i]*v[0]+m[i+4]*v[1]+m[i+8]*v[2]+m[i+12]);}return rotate(v.map((x,i)=>x*(n.scale?.[i]??1)),n.rotation||[0,0,0,1]).map((x,i)=>x+(n.translation?.[i]||0));}
function bounds(doc,extra={},bin){
 const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity],active=new Set();function visit(i,parents){if(active.has(i)||!doc.nodes?.[i])throw Error('Profile: invalid/cyclic node');active.add(i);const n=doc.nodes[i];if(n.mesh!==undefined)for(const p of doc.meshes[n.mesh].primitives){const a=doc.accessors[p.attributes.POSITION],view=doc.bufferViews[a.bufferView];if(a.componentType!==5126||a.type!=='VEC3'||!bin)throw Error('Profile: POSITION must be float32 VEC3');const stride=view.byteStride||12,start=(view.byteOffset||0)+(a.byteOffset||0);if(start+(a.count-1)*stride+12>(view.byteOffset||0)+view.byteLength)throw Error('Profile: position beyond view');for(let k=0;k<a.count;k++){let v=[0,1,2].map(j=>bin.readFloatLE(start+k*stride+j*4));for(const node of [n,...parents])v=transform(v,node);v=transform(v,extra);v.forEach((x,j)=>{if(!Number.isFinite(x))throw Error('Profile: non-finite position');min[j]=Math.min(min[j],x);max[j]=Math.max(max[j],x);});}}for(const c of n.children||[])visit(c,[n,...parents]);active.delete(i);}for(const i of doc.scenes?.[doc.scene??0]?.nodes||[])visit(i,[]);if(!Number.isFinite(min[0]))throw Error('Profile: empty scene');return {min,max};
}
module.exports={parse,pack,inspect,bounds,transform,rotate};
