'use strict';
// Existing tools only. Compact executed evidence, not copied historical test totals.
const fs=require('node:fs'),{spawnSync}=require('node:child_process'),E=require('./export.cjs');
const [python,report]=process.argv.slice(2);if(!python||!report)throw Error('Usage: node scripts/interop/validate.cjs python NEW-report.json');if(fs.existsSync(report))throw Error('Refusing evidence overwrite');
const cases=[],environment={...process.env,INTEROP_PYTHON:python};
function run(executable,args){const r=spawnSync(executable,args,{env:environment,encoding:'utf8',maxBuffer:8*1024*1024});const text=(r.stdout||'')+(r.stderr||''),totals=text.split(/\r?\n/).filter(s=>/^(?:ℹ (tests|pass|fail|cancelled|skipped|duration_ms)|Ran \d+ tests|OK$|FAILED)/.test(s));cases.push({command:[executable,...args],exitCode:r.status,totals,error:r.error?.message||null,...(r.status!==0?{failure:text.slice(-3500)}:{})});console.log(JSON.stringify(cases.at(-1)));return r.status===0;}
run(process.execPath,['--test','--test-concurrency=1',...['project','library','tracing','wall_assist','raw_wall_export','assets','surfaces','furniture-search','room-layout','interop'].map(n=>'tests/'+n+'.test.cjs')]);
run(process.execPath,['--test','--test-concurrency=1','--test-name-pattern=normalized Asset Lab cohort|F3 loader rejects|F3 missing reference|F3 core embedded JPEG|F3 cancellation|HTTP, hash, decode|cancel, invalid scale|390x844|844x390','tests/assets.browser.test.cjs','tests/surfaces.browser.test.cjs']);
for(const name of ['f2_readiness','f2_wall_evaluation','f2_raw_export'])run(python,['scripts/interop/run-python-tests.py','tests/'+name+'.test.py']);
const paths=['index.html','js/project-core.js','js/project-schema.js','js/project-library.js','js/asset-loader.mjs','js/surface-renderer.mjs','scripts/interop/export.cjs','scripts/interop/glb.cjs','scripts/interop/profiles.json','scripts/interop/blender-verify.py'];
const result={status:cases.every(c=>c.exitCode===0)?'PASS':'FAIL',environment:{node:process.version,platform:process.platform,arch:process.arch,python,chromium:process.env.CHROME||null,rendering:'Chromium automated desktop/touch emulation; no physical mobile performance claim'},cases,sourceFingerprints:Object.fromEntries(paths.map(p=>[p,E.sha(fs.readFileSync(p))])),independentPythonSchemaOracle:'NOT RUN: jsonschema not installed in available bundled Python; no installation. Fixture validation and schema-copy parity executed by actual Core validator/Node tests. No schema modification.'};fs.writeFileSync(report,JSON.stringify(result,null,2)+'\n',{flag:'wx'});if(result.status==='FAIL')process.exitCode=1;
